import http from 'node:http';
import { readFile, stat, readdir, mkdir } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT||4310);
const projectsRoot=process.env.RB_PROJECTS_DIR||path.join(os.homedir(),'RB','Projects');
const registry={
 'rb-workspace-intelligence':{name:'RB Workspace Intelligence',repo:'https://github.com/rennanbrasileiro/rb-workspace-intelligence.git',dir:'rb-workspace-intelligence',fallbackUrl:'http://127.0.0.1:4310'},
 'molde-3d-app':{name:'MOLDÊ',repo:'https://github.com/rennanbrasileiro/molde-3d-app.git',dir:'molde-3d-app',fallbackUrl:'http://127.0.0.1:4317'}
};
const protectedRoots=process.platform==='win32'?['C:\\Windows','C:\\Program Files','C:\\Program Files (x86)']:['/bin','/sbin','/usr','/etc','/System'];
const categoryByExt={'.pdf':'PDFs','.doc':'Documentos','.docx':'Documentos','.txt':'Documentos','.md':'Documentos','.xlsx':'Planilhas','.xls':'Planilhas','.csv':'Planilhas','.pptx':'Apresentações','.ppt':'Apresentações','.jpg':'Imagens','.jpeg':'Imagens','.png':'Imagens','.webp':'Imagens','.zip':'Arquivos compactados','.rar':'Arquivos compactados','.7z':'Arquivos compactados','.js':'Código','.ts':'Código','.tsx':'Código','.jsx':'Código','.py':'Código','.java':'Código','.cs':'Código','.sql':'Código'};
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));}
function tool(name){const cmd=process.platform==='win32'?'where':'which';return spawnSync(cmd,[name],{encoding:'utf8',shell:false}).status===0;}
function projectPath(p){return path.join(projectsRoot,p.dir)}
function safeSpawn(command,args,cwd){const child=spawn(command,args,{cwd,detached:true,stdio:'ignore',shell:false});child.unref();return child.pid;}
function runCommand(command,cwd,{detached=false}={}){if(!command)return {status:0,stdout:'Nenhum comando necessário.',stderr:''};if(detached){const child=process.platform==='win32'?spawn('cmd',['/d','/s','/c',command],{cwd,detached:true,stdio:'ignore'}):spawn('sh',['-lc',command],{cwd,detached:true,stdio:'ignore'});child.unref();return {status:0,stdout:`Processo iniciado · PID ${child.pid}`,stderr:''};}return process.platform==='win32'?spawnSync('cmd',['/d','/s','/c',command],{cwd,encoding:'utf8',maxBuffer:8*1024*1024}):spawnSync('sh',['-lc',command],{cwd,encoding:'utf8',maxBuffer:8*1024*1024});}
async function exists(p){try{await stat(p);return true}catch{return false}}
function assertUserPath(input){const resolved=path.resolve(input||'');if(!resolved)throw new Error('Informe um caminho.');if(protectedRoots.some(x=>resolved.toLowerCase().startsWith(path.resolve(x).toLowerCase())))throw new Error('Diretório protegido');const home=path.resolve(os.homedir());if(!resolved.toLowerCase().startsWith(home.toLowerCase()))throw new Error('No MVP, autorize somente caminhos dentro do seu usuário');return resolved;}
async function manifestFor(id,p){const dir=projectPath(p);try{return JSON.parse(await readFile(path.join(dir,'rb-project.json'),'utf8'))}catch{return {id,name:p.name,repository:p.repo,install:null,build:null,dev:null,start:null,localUrl:p.fallbackUrl,requires:['git']}}}
async function status(){const tools=Object.fromEntries(['git','node','code','python'].map(t=>[t,tool(t)]));const rows=[];for(const [id,p] of Object.entries(registry)){const dir=projectPath(p),cloned=await exists(path.join(dir,'.git')),manifest=await manifestFor(id,p);rows.push({id,name:manifest.name||p.name,repo:p.repo,path:dir,cloned,url:manifest.localUrl||p.fallbackUrl,type:manifest.type||'unknown',commands:{install:manifest.install,build:manifest.build,dev:manifest.dev,start:manifest.start}});}return{projectsRoot,tools,projects:rows};}
async function action(id,act){const p=registry[id];if(!p)throw new Error('Projeto desconhecido');const dir=projectPath(p);
 if(act==='clone-or-update'){await mkdir(projectsRoot,{recursive:true});if(await exists(path.join(dir,'.git'))){const r=spawnSync('git',['-C',dir,'pull','--ff-only'],{encoding:'utf8',maxBuffer:8*1024*1024});if(r.status)throw new Error(r.stderr||'git pull falhou');return r.stdout.trim()||'Atualizado';}const r=spawnSync('git',['clone',p.repo,dir],{encoding:'utf8',maxBuffer:8*1024*1024});if(r.status)throw new Error(r.stderr||'git clone falhou. Se o repositório for privado, autentique o Git/GitHub Credential Manager e tente novamente.');return 'Clonado';}
 if(!(await exists(dir)))throw new Error('Clone o projeto primeiro');const m=await manifestFor(id,p);
 if(act==='vscode'){if(!tool('code'))throw new Error('VS Code CLI não encontrado');safeSpawn('code',['-n',dir],dir);return 'VS Code aberto em uma janela nova';}
 if(act==='install'){const r=runCommand(m.install,dir);if(r.status)throw new Error(r.stderr||r.stdout||'Instalação falhou');return (r.stdout||'Dependências OK').trim().slice(-5000);}
 if(act==='build'){const r=runCommand(m.build,dir);if(r.status)throw new Error(r.stderr||r.stdout||'Build falhou');return (r.stdout||'Build concluído').trim().slice(-5000);}
 if(act==='run'){const command=m.dev||m.start;if(!command)throw new Error('Projeto não declarou comando dev/start em rb-project.json');return runCommand(command,dir,{detached:true}).stdout;}
 if(act==='browser'){const url=m.localUrl||p.fallbackUrl;safeSpawn(process.platform==='win32'?'cmd':process.platform==='darwin'?'open':'xdg-open',process.platform==='win32'?['/c','start','',url]:[url],dir);return 'Navegador aberto';}
 throw new Error('Ação não permitida');}
async function scanFolder(input){const resolved=assertUserPath(input),out=[];async function walk(dir,depth=0){if(depth>6||out.length>=3000)return;for(const e of await readdir(dir,{withFileTypes:true}).catch(()=>[])){if(['.git','node_modules','$Recycle.Bin','AppData'].includes(e.name))continue;const full=path.join(dir,e.name);if(e.isDirectory())await walk(full,depth+1);else{const s=await stat(full).catch(()=>null);if(s)out.push({path:full,name:e.name,size:s.size,modifiedAt:s.mtime.toISOString(),ext:path.extname(e.name).toLowerCase()});if(out.length>=3000)return;}}}await walk(resolved);return{root:resolved,count:out.length,files:out};}
function analyzeInventory(inv){const findings=[],plan=[];for(const f of inv.files){const year=new Date(f.modifiedAt).getFullYear(),category=categoryByExt[f.ext]||'Outros';const poor=/\b(final|novo|c[oó]pia|copy|documento|arquivo)(?:\s*\d+)?\b/i.test(path.parse(f.name).name)||/[()]{1}|\s{2,}/.test(f.name);if(poor)findings.push({type:'poor_filename',severity:'medium',path:f.path,message:'Nome pouco descritivo ou com marcador de versão informal.'});if(path.dirname(f.path)===inv.root){const proposed=path.join(inv.root,'Organizado',String(year),category,f.name);findings.push({type:'root_clutter',severity:'low',path:f.path,message:`Arquivo solto na raiz; candidato a ${year}/${category}.`});plan.push({operation:'MOVE_FILE',before:f.path,after:proposed,approved:false,executed:false});}}
 return{...inv,findings,plan,summary:{findings:findings.length,proposedOperations:plan.length,note:'PREVIEW apenas. Nenhum arquivo foi movido, renomeado ou apagado.'}};}
function readDocument(input){const resolved=assertUserPath(input);if(!tool('python'))throw new Error('Python não encontrado. Instale Python 3.11+ para Document Intelligence.');const script=path.join(root,'agent','reader.py');const r=spawnSync('python',[script,resolved],{encoding:'utf8',maxBuffer:4*1024*1024});let parsed;try{parsed=JSON.parse((r.stdout||'').trim())}catch{throw new Error(r.stderr||'O extrator não retornou JSON válido.');}if(r.status||!parsed.ok)throw new Error(parsed.error||r.stderr||'Falha ao ler documento');return parsed.document;}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');if(u.pathname==='/api/status')return json(res,200,await status());if(req.method==='POST'&&u.pathname.startsWith('/api/project/')){const [, , ,id,act]=u.pathname.split('/');return json(res,200,{ok:true,message:await action(id,act)});}if(req.method==='POST'&&['/api/scan','/api/analyze','/api/document/read'].includes(u.pathname)){let b='';for await(const c of req)b+=c;const body=JSON.parse(b||'{}');if(u.pathname==='/api/document/read')return json(res,200,{ok:true,document:readDocument(body.path)});const inv=await scanFolder(body.path);return json(res,200,u.pathname==='/api/analyze'?analyzeInventory(inv):inv);}
 let base=u.pathname.startsWith('/devhub')?path.join(root,'devhub'):path.join(root,'app');let rel=u.pathname.startsWith('/devhub')?u.pathname.replace(/^\/devhub\/?/,''):u.pathname.replace(/^\//,'');if(!rel)rel='index.html';const file=path.join(base,rel);if(!file.startsWith(base))throw new Error('invalid path');const body=await readFile(file);const ext=path.extname(file);res.writeHead(200,{'content-type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':ext==='.json'?'application/json; charset=utf-8':'text/plain; charset=utf-8','cache-control':'no-store'});res.end(body);}catch(e){if((req.url||'').startsWith('/api/'))return json(res,400,{ok:false,error:e.message});res.writeHead(404);res.end('Not found');}});
server.listen(port,'127.0.0.1',()=>console.log(`RB Workspace Intelligence: http://127.0.0.1:${port} · Dev Hub: http://127.0.0.1:${port}/devhub/`));
