import {$,post,toast,esc,fmtBytes,setBusy} from './common.js';
let currentScan=null,currentPlan=null,lastPath='';

function labelFinding(t){return({poor_filename:'Nome pouco claro',organization_candidate:'Candidato à organização',duplicate:'Duplicado confirmado',content_classification:'Conteúdo identificado',document_read_error:'Leitura documental'})[t]||t}

function ensureGuide(){
  if(document.getElementById('organizerGuide'))return;
  const focus=document.querySelector('#organize .focus-action');
  focus?.insertAdjacentHTML('beforebegin',`<div class="organizer-guide" id="organizerGuide"><div class="guide-steps">${[
    ['1','Escolher pasta'],['2','Ler e classificar'],['3','Revisar grupos'],['4','Selecionar'],['5','Aplicar'],['6','Resultado']
  ].map(([n,t])=>`<div class="guide-step" data-guide-step="${n}"><span>${n}</span><b>${t}</b></div>`).join('')}</div><div class="next-action" id="organizerNext"><b>Próximo passo</b><span>Escolha uma pasta para começar.</span></div></div>`);
  document.querySelector('#organize .plan-panel')?.insertAdjacentHTML('afterend',`<article class="panel organizer-result" id="organizerResult" hidden><div class="panel-head"><div><span class="kicker">RESULTADO</span><h3>O que aconteceu</h3></div><span class="status ok" id="organizerResultStatus">concluído</span></div><div id="organizerResultBody"></div><div class="result-actions"><button class="primary" id="reanalyzeBtn">Analisar novamente</button><button class="secondary" id="resultHistoryBtn">Ver histórico</button><button class="ghost" id="resultRollbackBtn">Desfazer esta organização</button></div></article>`);
}
function guide(step,message,doneThrough=step-1){
  ensureGuide();
  document.querySelectorAll('.guide-step').forEach(el=>{const n=Number(el.dataset.guideStep);el.classList.toggle('done',n<=doneThrough);el.classList.toggle('active',n===step);});
  const n=document.getElementById('organizerNext');if(n)n.innerHTML=`<b>Próximo passo</b><span>${esc(message)}</span>`;
}
function renderScan(s){$('scanStatus').className='status ok';$('scanStatus').textContent=s.truncated?'parcial':'concluído';const total=s.files.reduce((a,f)=>a+f.size,0),cats={};s.files.forEach(f=>cats[f.category]=(cats[f.category]||0)+1);const skipped=s.skipped||{};$('scanSummary').className='';$('scanSummary').innerHTML=`<div class="inventory-grid"><div><strong>${s.fileCount}</strong><span>arquivos úteis lidos</span></div><div><strong>${s.folderCount}</strong><span>pastas úteis</span></div><div><strong>${fmtBytes(total)}</strong><span>volume analisado</span></div></div><div class="meta-line">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<span>${esc(k)} <b>${v}</b></span>`).join('')}</div>${(skipped.technicalCount||skipped.repositoryCount)?`<div class="protected-summary"><b>Protegido automaticamente</b><span>${skipped.technicalCount||0} pastas técnicas/cache · ${skipped.repositoryCount||0} repositórios Git preservados</span></div>`:''}`;}
function updateSelected(){const checked=[...document.querySelectorAll('.op-check:checked')],moves=checked.filter(x=>x.dataset.type==='MOVE_FILE').length,quarantine=checked.length-moves;$('selectedCount').textContent=checked.length;$('executeBtn').disabled=checked.length===0;const summary=document.getElementById('selectionSummary');if(summary)summary.textContent=`${moves} movimentos${quarantine?` · ${quarantine} quarentenas`:''}`;if(currentPlan?.operations?.length){if(checked.length)guide(5,`Você selecionou ${checked.length} operação(ões). Clique em “Aplicar selecionadas”.`,4);else guide(4,'Selecione um grupo, marque arquivos individualmente ou use “Selecionar todos os movimentos”.',3)}}
function opRow(o){return`<div class="plan-row"><input type="checkbox" class="op-check" data-type="${esc(o.type)}" data-area="${esc(o.area||'Outros')}" value="${esc(o.id)}" ${o.recommended?'checked':''}><span><b>${o.type==='QUARANTINE_FILE'?'Quarentena':'Mover'}</b><br><small>${esc(o.reason)}</small></span><code>${esc(o.before)}</code><span class="arrow">→</span><code class="to">${esc(o.after)}</code><span class="confidence">${esc(o.confidence)}</span></div>`;}
function bindPlanControls(){document.querySelectorAll('.op-check').forEach(c=>c.onchange=updateSelected);document.querySelectorAll('.select-area').forEach(b=>b.onclick=()=>{document.querySelectorAll(`.op-check[data-area="${CSS.escape(b.dataset.area)}"][data-type="MOVE_FILE"]`).forEach(c=>c.checked=true);updateSelected()});document.getElementById('selectAllMovesBtn')?.addEventListener('click',()=>{document.querySelectorAll('.op-check[data-type="MOVE_FILE"]').forEach(c=>c.checked=true);updateSelected()});document.getElementById('clearAllBtn')?.addEventListener('click',()=>{document.querySelectorAll('.op-check').forEach(c=>c.checked=false);updateSelected()});}
function renderPlan(p){const di=p.documentIntelligence||{},all=p.findings||[],content=all.filter(f=>f.type==='content_classification'),decision=all.filter(f=>f.type!=='content_classification'&&f.type!=='organization_candidate'),contentBuckets={};for(const d of di.documents||[])if(!d.error)contentBuckets[d.bucket]=(contentBuckets[d.bucket]||0)+1;$('findingCount').textContent=`${decision.length} alertas · ${p.operations.length} sugestões`;$('findingCount').className=`status ${decision.length?'warn':'ok'}`;const docBanner=di.count!==undefined?`<div class="document-intel-banner"><b>${di.readComplete||0} documentos lidos integralmente</b><span>${Object.entries(contentBuckets).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')||'sem classificação de conteúdo'}${di.failed?` · ${di.failed} falhas de leitura`:''}</span></div>`:'';$('findings').className='';$('findings').innerHTML=docBanner+(decision.length?decision.slice(0,100).map(f=>`<div class="finding"><span class="severity ${esc(f.severity||'')}"></span><div><strong>${esc(labelFinding(f.type))}</strong><small>${esc(f.message||'')}${f.path?` · ${esc(f.path)}`:''}</small></div></div>`).join(''):'<div class="empty-state success">Nenhum alerta crítico. Revise abaixo apenas as sugestões de organização.</div>')+(content.length?`<details class="content-details"><summary>Ver ${content.length} classificações documentais individuais</summary><div class="content-detail-list">${content.slice(0,250).map(f=>`<div><b>${esc(f.message||'')}</b><span>${esc(f.path||'')}</span></div>`).join('')}</div></details>`:'');
  if(!p.operations.length){$('plan').className='';$('plan').innerHTML='<div class="empty-state success"><b>Nenhuma movimentação pendente pelas regras atuais.</b><br>Isso pode significar que a pasta já foi organizada ou que os itens restantes estão protegidos/técnicos.</div>';$('selectedCount').textContent='0';$('executeBtn').disabled=true;guide(6,'A pasta não tem movimentações pendentes. Você pode escolher outra pasta ou conferir o Histórico.',5);return;}
  const groups={};for(const o of p.operations){const area=o.area||'Outros';(groups[area]??=[]).push(o);}const ordered=Object.entries(groups).sort(([a],[b])=>a==='Duplicados'?1:b==='Duplicados'?-1:a.localeCompare(b,'pt-BR'));
  $('plan').className='';$('plan').innerHTML=`<div class="plan-master-toolbar"><div><b>Organização por áreas</b><span id="selectionSummary">revise e selecione o que deseja mover</span></div><div><button class="primary small" id="selectAllMovesBtn">Selecionar todos os movimentos</button><button class="ghost small" id="clearAllBtn">Limpar seleção</button></div></div>${ordered.map(([area,ops])=>`<section class="plan-group"><div class="plan-group-head"><div><span class="area-dot"></span><strong>${esc(area)}</strong><small>${ops.length} sugestão(ões)${area==='Duplicados'?' · revisão separada':''}</small></div>${area!=='Duplicados'?`<button class="ghost small select-area" data-area="${esc(area)}">Selecionar grupo</button>`:''}</div>${ops.map(opRow).join('')}</section>`).join('')}`;bindPlanControls();$('selectRecommendedBtn').disabled=false;guide(4,'Revise os grupos. Se quiser aceitar os movimentos propostos, clique em “Selecionar todos os movimentos”.',3);updateSelected();}
function renderResult(tx){ensureGuide();const box=document.getElementById('organizerResult'),body=document.getElementById('organizerResultBody'),status=document.getElementById('organizerResultStatus');box.hidden=false;status.className=`status ${tx.summary.failed?'warn':'ok'}`;status.textContent=tx.summary.failed?'com alertas':'concluído';const ok=(tx.operations||[]).filter(o=>o.status==='completed'),failed=(tx.operations||[]).filter(o=>o.status==='failed');body.innerHTML=`<div class="result-metrics"><div><strong>${ok.length}</strong><span>movidos</span></div><div><strong>${failed.length}</strong><span>falharam</span></div></div><p class="result-copy">A organização foi registrada no Histórico e pode ser desfeita. Abaixo estão alguns destinos efetivamente usados.</p><div class="result-list">${ok.slice(0,12).map(o=>`<div><span>✓</span><code>${esc(o.after||'')}</code></div>`).join('')||'<div>Nenhum movimento concluído.</div>'}${failed.slice(0,6).map(o=>`<div class="failed"><span>!</span><code>${esc(o.before)} · ${esc(o.error||'falhou')}</code></div>`).join('')}</div>`;document.getElementById('reanalyzeBtn').onclick=()=>analyzeFolder(lastPath,window.__rbRefreshSystem||(()=>Promise.resolve()));document.getElementById('resultHistoryBtn').onclick=()=>window.__rbGo?.('history');document.getElementById('resultRollbackBtn').onclick=async()=>{if(!confirm('Desfazer esta organização agora?'))return;try{await post(`/api/transactions/${tx.id}/rollback`);toast('Organização desfeita.');box.hidden=true;await (window.__rbRefreshSystem?.()||Promise.resolve());if(lastPath)await analyzeFolder(lastPath,window.__rbRefreshSystem||(()=>Promise.resolve()));}catch(e){toast(e.message)}};guide(6,`Concluído: ${ok.length} arquivo(s) movido(s). Agora você pode reanalisar a mesma pasta, conferir o histórico ou desfazer.`,5);box.scrollIntoView({behavior:'smooth',block:'start'});}
async function analyzeFolder(path,refreshSystem){if(!path)return toast('Escolha uma pasta.');lastPath=path;document.getElementById('organizerResult')&&(document.getElementById('organizerResult').hidden=true);$('folderPath').value=path;$('selectedFolderLabel').textContent=path;$('selectedFolderHelp').textContent='Mapeando áreas, preservando pastas técnicas e lendo documentos suportados. Nenhum arquivo será alterado.';guide(2,'Aguarde a leitura e classificação. Nenhum arquivo será movido nesta etapa.',1);$('scanStatus').className='status neutral';$('scanStatus').textContent='inventariando';$('scanSummary').className='loading-box';$('scanSummary').innerHTML='<span class="spinner"></span> Separando arquivos úteis de caches, dependências e repositórios…';$('findings').className='loading-box';$('findings').textContent='Depois do inventário, o Workspace classificará o conteúdo por área e assunto.';$('plan').className='loading-box';$('plan').textContent='Preparando uma árvore de organização por partes…';try{const sj=await post('/api/workspace/scan',{path,spaceId:$('spaceSelect').value});currentScan=sj.scan;renderScan(currentScan);$('scanStatus').textContent='lendo documentos';const aj=await post('/api/workspace/analyze',{scanId:currentScan.id,spaceId:$('spaceSelect').value});currentPlan=aj.plan;renderPlan(currentPlan);$('scanStatus').textContent='concluído';$('selectedFolderHelp').textContent=`Análise concluída: ${currentPlan.documentIntelligence?.readComplete||0} documentos lidos · ${currentPlan.operations?.filter(o=>o.type==='MOVE_FILE').length||0} movimentos sugeridos por área.`;toast(`Análise pronta · ${currentPlan.operations?.length||0} sugestões.`);await refreshSystem();}catch(e){$('scanStatus').className='status warn';$('scanStatus').textContent='erro';$('scanSummary').className='empty-state';$('scanSummary').textContent=e.message;guide(1,`A análise encontrou um erro: ${e.message}. Escolha a pasta novamente ou tente outra.`,0);toast(e.message)}}
export function initFileOrganizer({go,refreshSystem}){ensureGuide();window.__rbGo=go;window.__rbRefreshSystem=refreshSystem;guide(1,'Clique em “Selecionar pasta e analisar”.',0);const pick=async()=>{setBusy('pickAnalyzeBtn',true,'Abrindo seletor do Windows…');guide(1,'O seletor do Windows está aberto. Escolha a pasta e confirme.',0);try{const j=await post('/api/pick/folder');if(!j.path){guide(1,'Nenhuma pasta foi escolhida. Clique novamente quando quiser.',0);return toast('Nenhuma pasta selecionada.');}await analyzeFolder(j.path,refreshSystem);}catch(e){guide(1,`Não consegui abrir/usar o seletor: ${e.message}`,0);toast(e.message)}finally{setBusy('pickAnalyzeBtn',false,'Selecionar pasta e analisar')}};$('pickAnalyzeBtn').onclick=pick;$('homeAnalyzeBtn').onclick=()=>{go('organize');setTimeout(pick,80)};$('manualAnalyzeBtn').onclick=()=>analyzeFolder($('folderPath').value.trim(),refreshSystem);$('selectRecommendedBtn').onclick=()=>{if(!currentPlan)return;const rec=new Set(currentPlan.operations.filter(o=>o.recommended&&o.type==='MOVE_FILE').map(o=>o.id));document.querySelectorAll('.op-check').forEach(c=>c.checked=rec.has(c.value));updateSelected()};$('executeBtn').onclick=async()=>{const ids=[...document.querySelectorAll('.op-check:checked')].map(x=>x.value);if(!ids.length)return toast('Nenhuma operação selecionada. Escolha um grupo ou use “Selecionar todos os movimentos”.');if(!confirm(`Aplicar ${ids.length} operação(ões)?\n\nNada será excluído. Movimentos ficam auditados e podem ser desfeitos; duplicados selecionados vão apenas para quarentena.`))return;guide(5,`Aplicando ${ids.length} operação(ões). Aguarde o resultado.`,4);setBusy('executeBtn',true,'Aplicando…');try{const j=await post('/api/workspace/execute',{planId:currentPlan.id,operationIds:ids});toast(`${j.transaction.summary.completed} operação(ões) concluída(s).`);await refreshSystem();renderResult(j.transaction)}catch(e){guide(5,`A execução parou com erro: ${e.message}`,4);toast(e.message)}finally{setBusy('executeBtn',false,'Aplicar selecionadas')}};}
