import {$,api,post,toast,esc,fmtBytes,fmtDate} from './common.js';

let state={q:'',status:'all',offset:0,limit:100,data:null,loading:false};
function ensureUi(){
  if($('analyzedInventory'))return;
  const anchor=document.querySelector('#organize .analysis-grid');if(!anchor)return;
  anchor.insertAdjacentHTML('afterend',`<article class="panel analyzed-inventory" id="analyzedInventory" hidden><div class="panel-head"><div><span class="kicker">ACERVO ANALISADO · SOMENTE LEITURA</span><h3>Veja tudo que entrou na análise</h3><p>Pesquise o arquivo atual mesmo quando não existe sugestão de movimento.</p></div><span class="status neutral" id="inventoryStatus">aguardando</span></div><div class="inventory-overview" id="inventoryOverview"></div><div class="inventory-controls"><input id="inventorySearch" placeholder="Buscar nome, caminho, tema, conteúdo ou destino"><select id="inventoryFilter"><option value="all">Todos os arquivos</option><option value="suggestion">Com sugestão</option><option value="pending">Pendentes de revisão</option><option value="decided">Com decisão registrada</option><option value="no_action">Sem ação sugerida</option><option value="reference">Referências protegidas</option><option value="quarantine">Quarentena</option></select></div><div class="inventory-list" id="inventoryList"></div><div class="inventory-pagination" id="inventoryPagination"></div></article>`);
  let timer=null;$('inventorySearch').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=e.target.value||'';state.offset=0;load();},220)};$('inventoryFilter').onchange=e=>{state.status=e.target.value||'all';state.offset=0;load();};
}
function statusLabel(i){return({no_action:'sem ação',pending:'pendente',approved:'aprovado',adjusted:'ajustado',excluded:'não mover',quarantine:'quarentena'})[i.reviewStatus]||i.reviewStatus||'arquivo';}
function docLine(i){const d=i.document;if(d?.summary)return d.summary;if(d?.topic||d?.area)return[d.area,d.topic,d.bucket].filter(Boolean).join(' · ');return i.category||i.ext||'Arquivo';}
function renderOverview(d){const c=d.counts||{},p=d.protected||{};$('inventoryOverview').innerHTML=`<div><strong>${c.total||0}</strong><span>arquivos no acervo</span></div><div><strong>${c.withSuggestion||0}</strong><span>com sugestão</span></div><div><strong>${c.noAction||0}</strong><span>sem ação sugerida</span></div><div><strong>${c.pending||0}</strong><span>pendentes</span></div><div><strong>${c.references||0}</strong><span>referências protegidas</span></div><div><strong>${(p.projects||0)+(p.technical||0)+(p.system||0)}</strong><span>itens técnicos protegidos</span></div>`;}
function row(i){return`<div class="inventory-item" data-path="${esc(i.path)}"><div class="inventory-file"><div class="inventory-name"><strong>${esc(i.name)}</strong><span class="inventory-state ${esc(i.reviewStatus)}">${esc(statusLabel(i))}</span>${i.referenceRisk?'<span class="inventory-reference">referência</span>':''}</div><code>${esc(i.path)}</code><small>${esc(docLine(i))} · ${fmtBytes(i.size||0)}${i.modifiedAt?` · ${esc(fmtDate(i.modifiedAt))}`:''}</small>${i.hasSuggestion?`<div class="inventory-destination"><span>proposta</span><code>${esc(i.destination||'')}</code></div>`:'<div class="inventory-no-action">Nenhuma movimentação foi sugerida. O arquivo continua exatamente onde está.</div>'}</div><div class="inventory-actions"><button class="ghost tiny" data-act="open">↗ Abrir</button><button class="ghost tiny" data-act="reveal">⌖ Localizar</button><button class="ghost tiny" data-act="read">▤ Ler</button>${i.operationId?`<button class="secondary tiny" data-act="review" data-op="${esc(i.operationId)}">⌕ Revisar proposta</button>`:''}</div></div>`;}
function render(d){ensureUi();const box=$('analyzedInventory');box.hidden=false;$('inventoryStatus').className='status ok';$('inventoryStatus').textContent=`${d.matched} exibíveis`;renderOverview(d);$('inventoryList').innerHTML=d.items.length?d.items.map(row).join(''):'<div class="empty-state">Nenhum arquivo corresponde à busca ou filtro atual.</div>';const start=d.matched?d.offset+1:0,end=d.offset+d.items.length;$('inventoryPagination').innerHTML=`<span>Mostrando ${start}-${end} de ${d.matched}</span><div><button class="ghost tiny" id="inventoryPrev" ${d.offset<=0?'disabled':''}>← Anterior</button><button class="ghost tiny" id="inventoryNext" ${!d.hasMore?'disabled':''}>Próxima →</button></div>`;$('inventoryPrev').onclick=()=>{state.offset=Math.max(0,state.offset-state.limit);load();};$('inventoryNext').onclick=()=>{state.offset+=state.limit;load();};bindRows();}
function bindRows(){document.querySelectorAll('#inventoryList .inventory-item').forEach(r=>{r.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const act=b.dataset.act,path=r.dataset.path;try{if(act==='open'){await post('/api/review/open',{path});toast('Abrindo arquivo original.');}if(act==='reveal'){await post('/api/review/reveal',{path});toast('Arquivo localizado no Explorador.');}if(act==='read'){window.__rbGo?.('documents');if($('docPath'))$('docPath').value=path;setTimeout(()=>$('readDocBtn')?.click(),60);}if(act==='review'){const search=$('reviewQueueSearch'),filter=$('reviewQueueFilter'),start=$('reviewStartQueue');window.__rbGo?.('organize');if(filter){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}));}if(search){search.value=path;search.dispatchEvent(new Event('input',{bubbles:true}));}setTimeout(()=>start?.click(),80);}}catch(e){toast(e.message)}});});}
async function load(){ensureUi();if(state.loading)return;state.loading=true;const box=$('analyzedInventory');if(box){box.hidden=false;$('inventoryStatus').className='status neutral';$('inventoryStatus').textContent='carregando';}try{const qs=new URLSearchParams({q:state.q,status:state.status,offset:String(state.offset),limit:String(state.limit)}),j=await api(`/api/review/inventory?${qs}`);state.data=j.inventory;render(j.inventory);}catch(e){if(box){$('inventoryStatus').className='status neutral';$('inventoryStatus').textContent='indisponível';$('inventoryList').innerHTML=`<div class="empty-state">${esc(e.message)}</div>`;} }finally{state.loading=false;}}
export function initInventoryBrowser(){ensureUi();load();document.addEventListener('rbwi:api-response',e=>{const d=e.detail||{};if(d.url?.startsWith('/api/organizer/jobs/')&&d.data?.job?.status==='completed'){state.offset=0;setTimeout(load,80);}});}
