import {$,api,post,toast,esc,fmtDate,fmtBytes,setBusy} from './common.js';
import {initFileOrganizer} from './files.js';
import {initProjects,refreshProjects} from './projects.js';
import {initV17Enhancements} from './v17.js';
import {initQuarantineHotfix} from './quarantine-hotfix.js';
import {initRecoveryCenter} from './recovery.js';
import {initReviewExperience} from './review.js';
import {initExecutionReviewGuard} from './execution-review-guard.js';
import {initInventoryBrowser} from './inventory.js';
import {initNameSuggestions} from './name-suggestions.js';
const v12=document.createElement('link');v12.rel='stylesheet';v12.href='/v12.css';document.head.appendChild(v12);
const v16=document.createElement('link');v16.rel='stylesheet';v16.href='/v16.css';document.head.appendChild(v16);
const reviewCss=document.createElement('link');reviewCss.rel='stylesheet';reviewCss.href='/review.css';document.head.appendChild(reviewCss);
const guardCss=document.createElement('link');guardCss.rel='stylesheet';guardCss.href='/execution-review-guard.css';document.head.appendChild(guardCss);
const inventoryCss=document.createElement('link');inventoryCss.rel='stylesheet';inventoryCss.href='/inventory.css';document.head.appendChild(inventoryCss);
const nameCss=document.createElement('link');nameCss.rel='stylesheet';nameCss.href='/name-suggestions.css';document.head.appendChild(nameCss);
const historyCss=document.createElement('link');historyCss.rel='stylesheet';historyCss.href='/history-trace.css';document.head.appendChild(historyCss);
let state=null,currentDocText='';
function primeUx(){
  if($('versionLabel'))$('versionLabel').textContent='carregando versão validada…';
  const intro=document.querySelector('#organize .section-intro');if(intro){const h=intro.querySelector('h2'),p=intro.querySelector('p');if(h)h.textContent='Entenda, revise e só então organize.';if(p)p.textContent='O Workspace lê a pasta, identifica conteúdo e contexto e monta uma proposta rastreável. Revise nomes, destinos e arquivos antes de qualquer alteração física.';}
  const planTitle=document.querySelector('#organize .plan-panel .panel-head h3');if(planTitle)planTitle.textContent='Revise cada destino antes de aplicar';
  const execute=$('executeBtn');if(execute)execute.textContent='Revisar segurança e aplicar';
  const hero=document.querySelector('#overview .hero-card');if(hero){const h=hero.querySelector('h2'),p=hero.querySelector('p');if(h)h.textContent='Entenda seus arquivos antes de reorganizá-los.';if(p)p.textContent='Analise, leia, ajuste e rastreie cada decisão. O Workspace só altera arquivos depois da sua seleção, preflight e checkpoint de segurança.';}
}
export function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$('pageTitle').textContent={overview:'Início',organize:'Organizar arquivos',projects:'Projetos locais',documents:'Inspecionar documento',recovery:'Recuperação',history:'Histórico'}[id]||id;if(id==='history')renderTransactions();if(id==='projects')refreshProjects(null,n=>$('metricProjects').textContent=n);}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.addEventListener('click',async e=>{const trace=e.target.closest('[data-trace-action]');if(trace){e.preventDefault();const action=trace.dataset.traceAction,path=trace.dataset.path||'';try{if(action==='open')await post('/api/review/open',{path});if(action==='reveal')await post('/api/review/reveal',{path});if(action==='copy'){await navigator.clipboard.writeText(path);toast('Caminho copiado.');return;}toast(action==='open'?'Abrindo arquivo atual.':'Arquivo localizado no Explorador.');}catch(err){toast(err.message)}return;}if(e.target.closest('.project-item,.clone-gh'))setTimeout(()=>document.getElementById('projectWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'}),650)});
async function refreshSystem(){state=await api('/api/system');renderState();}
function renderState(){if(!state)return;const build=state.buildCommit?` · build ${state.buildCommit.slice(0,8)}`:'';$('versionLabel').textContent=`v${state.version}${build} · local-first`;$('machineName').textContent=state.machine.hostname;$('metricSpaces').textContent=state.counts.spaces;$('metricScans').textContent=state.counts.scans;$('metricTransactions').textContent=state.counts.transactions;renderSpaces();renderTransactions();}
function renderSpaces(){const spaces=state.spaces||[],selected=$('spaceSelect').value;$('spaceSelect').innerHTML=spaces.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');if(spaces.some(s=>s.id===selected))$('spaceSelect').value=selected;}
function selectedSpace(){return(state?.spaces||[]).find(s=>s.id===$('spaceSelect').value)}
function openSpace(s){$('spaceId').value=s?.id||'';$('spaceName').value=s?.name||'';$('spaceDescription').value=s?.description||'';$('spaceBasePath').value=s?.basePath||'';$('spacePolicy').value=s?.policy||'';$('spaceModal').classList.add('show')}
function closeSpace(){$('spaceModal').classList.remove('show')}
$('editSpaceBtn').onclick=()=>openSpace(selectedSpace());$('closeSpaceModal').onclick=$('cancelSpaceBtn').onclick=closeSpace;$('saveSpaceBtn').onclick=async()=>{try{await post('/api/spaces',{id:$('spaceId').value||undefined,name:$('spaceName').value,description:$('spaceDescription').value,basePath:$('spaceBasePath').value,policy:$('spacePolicy').value});closeSpace();await refreshSystem();toast('Contexto salvo.')}catch(e){toast(e.message)}};
$('pickFileBtn').onclick=async()=>{setBusy('pickFileBtn',true,'Abrindo…');try{const j=await post('/api/pick/file');if(j.path)$('docPath').value=j.path;else toast('Nenhum documento selecionado.')}catch(e){toast(e.message)}finally{setBusy('pickFileBtn',false,'Escolher arquivo')}};
$('readDocBtn').onclick=async()=>{const p=$('docPath').value.trim();if(!p)return toast('Escolha um documento.');setBusy('readDocBtn',true,'Lendo documento inteiro…');try{const d=(await post('/api/document/read',{path:p})).document;currentDocText=d.text||'';$('docTitle').textContent=d.name;$('docText').textContent=d.text||d.warning||'Nenhum texto extraído.';$('docMeta').className='doc-meta';$('docMeta').innerHTML=`<dl><dt>Formato</dt><dd>${esc(d.ext)}</dd><dt>Tamanho</dt><dd>${fmtBytes(d.size)}</dd><dt>Método</dt><dd>${esc(d.method)}</dd><dt>SHA-256</dt><dd><code>${esc(d.sha256)}</code></dd><dt>Texto</dt><dd>${d.textLength.toLocaleString('pt-BR')} caracteres</dd><dt>Leitura</dt><dd>${d.complete?'Integral ✓':'Parcial'}</dd><dt>Integridade</dt><dd>Original intocado ✓</dd></dl>${d.warning?`<p class="warning">${esc(d.warning)}</p>`:''}`;$('copyDocBtn').disabled=!currentDocText;toast('Documento lido integralmente em modo somente leitura.')}catch(e){toast(e.message)}finally{setBusy('readDocBtn',false,'Ler documento inteiro')}};$('copyDocBtn').onclick=async()=>{await navigator.clipboard.writeText(currentDocText);toast('Texto copiado.')};
function txStatusLabel(status){return({completed:'concluída',completed_with_errors:'concluída com alertas',cancelled:'cancelada',failed:'falhou',rolled_back:'originais restaurados',rollback_with_errors:'restauração com alertas'})[status]||status||'transação';}
function opTypeLabel(type){return type==='QUARANTINE_FILE'?'Quarentena':type==='MOVE_FILE'?'Organização':type||'Operação';}
function traceOperation(o){const after=o.after||o.requestedAfter||'',current=after||o.before,ok=o.status==='completed';return`<div class="transaction-op trace-operation" data-trace-text="${esc(`${o.before||''} ${after} ${o.type||''}`)}"><div class="trace-op-head"><div><b>${esc(opTypeLabel(o.type))}</b><span class="status ${ok?'ok':o.status==='failed'?'warn':'neutral'}">${esc(o.status||'registrada')}</span></div>${o.sourceRemoved===false?'<small>origem preservada</small>':''}</div><div class="trace-path-grid"><div><small>ORIGEM</small><code>${esc(o.before||'—')}</code></div><span class="trace-arrow">→</span><div><small>${o.type==='QUARANTINE_FILE'?'QUARENTENA / DESTINO':'DESTINO'}</small><code>${esc(after||'—')}</code></div></div>${o.warning?`<div class="trace-note warning">${esc(o.warning)}</div>`:''}${o.error?`<div class="trace-note warning">${esc(o.error)}</div>`:''}<div class="trace-op-actions">${current?`<button class="ghost tiny" data-trace-action="open" data-path="${esc(current)}">↗ Abrir atual</button><button class="ghost tiny" data-trace-action="reveal" data-path="${esc(current)}">⌖ Localizar atual</button><button class="ghost tiny" data-trace-action="copy" data-path="${esc(current)}">⧉ Copiar caminho</button>`:''}</div></div>`;}
function bindHistorySearch(){const input=$('historyTraceSearch'),count=$('historyTraceCount');if(!input)return;const apply=()=>{const q=(input.value||'').trim().toLocaleLowerCase('pt-BR');let visibleOps=0;document.querySelectorAll('#transactions .transaction').forEach(card=>{let cardVisible=0;card.querySelectorAll('.trace-operation').forEach(op=>{const match=!q||(op.dataset.traceText||op.textContent||'').toLocaleLowerCase('pt-BR').includes(q);op.hidden=!match;if(match){visibleOps++;cardVisible++;}});card.hidden=q&&cardVisible===0;});if(count)count.textContent=q?`${visibleOps} operação(ões) encontrada(s)`: `${document.querySelectorAll('#transactions .trace-operation').length} operação(ões) rastreáveis`;};input.oninput=apply;apply();}
function renderTransactions(){if(!state)return;const txs=state.transactions||[],totalOps=txs.reduce((n,t)=>n+(t.operations?.length||0),0),toolbar=`<div class="history-trace-toolbar"><div><b>Mapa origem → destino</b><span>Encontre um arquivo pelo nome, caminho antigo ou caminho novo.</span></div><input id="historyTraceSearch" placeholder="Buscar arquivo, origem ou destino"><small id="historyTraceCount">${totalOps} operação(ões) rastreáveis</small></div>`;$('transactions').innerHTML=toolbar+(txs.length?txs.map(t=>`<article class="transaction"><div class="transaction-head"><div><h3>${esc(txStatusLabel(t.status))} · ${t.summary?.completed||0}/${t.summary?.requested||t.operations?.length||0} concluídas</h3><small>${fmtDate(t.createdAt)} · ${esc(t.id)}${t.checkpointId?` · checkpoint ${esc(t.checkpointId)}`:''}</small></div>${!['rolled_back'].includes(t.status)?`<button class="ghost rollback" data-id="${esc(t.id)}">Restaurar caminhos originais</button>`:'<span class="status ok">originais restaurados</span>'}</div><div class="transaction-ops">${(t.operations||[]).map(traceOperation).join('')}</div></article>`).join(''):'<div class="empty-state">Ainda não há operações executadas.</div>');document.querySelectorAll('.rollback').forEach(b=>b.onclick=()=>rollback(b.dataset.id));bindHistorySearch();}
async function rollback(id){if(!confirm('Restaurar os caminhos originais desta transação?\n\nA cópia organizada será preservada e nenhum arquivo existente será sobrescrito.'))return;try{await post(`/api/transactions/${id}/rollback`);await refreshSystem();toast('Restauração segura processada.')}catch(e){toast(e.message)}}
async function boot(){primeUx();await refreshSystem();initFileOrganizer({go,refreshSystem});initReviewExperience();initExecutionReviewGuard();initInventoryBrowser();initNameSuggestions();initV17Enhancements();initQuarantineHotfix();initRecoveryCenter({go});initProjects({onCount:n=>$('metricProjects').textContent=n});}
boot().catch(e=>toast(e.message));
