import {$,api,post,toast,esc,fmtDate,fmtBytes,setBusy} from './common.js';
import {initFileOrganizer} from './files.js';
import {initProjects,refreshProjects} from './projects.js';
import {initV17Enhancements} from './v17.js';
import {initQuarantineHotfix} from './quarantine-hotfix.js';
const v12=document.createElement('link');v12.rel='stylesheet';v12.href='/v12.css';document.head.appendChild(v12);
const v16=document.createElement('link');v16.rel='stylesheet';v16.href='/v16.css';document.head.appendChild(v16);
let state=null,currentDocText='';
export function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$('pageTitle').textContent={overview:'Início',organize:'Organizar arquivos',projects:'Projetos locais',documents:'Inspecionar documento',history:'Histórico'}[id]||id;if(id==='history')renderTransactions();if(id==='projects')refreshProjects(null,n=>$('metricProjects').textContent=n);}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.addEventListener('click',e=>{if(e.target.closest('.project-item,.clone-gh'))setTimeout(()=>document.getElementById('projectWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'}),650)});
async function refreshSystem(){state=await api('/api/system');renderState();}
function renderState(){if(!state)return;$('versionLabel').textContent=`v${state.version} · local-first`;$('machineName').textContent=state.machine.hostname;$('metricSpaces').textContent=state.counts.spaces;$('metricScans').textContent=state.counts.scans;$('metricTransactions').textContent=state.counts.transactions;renderSpaces();renderTransactions();}
function renderSpaces(){const spaces=state.spaces||[],selected=$('spaceSelect').value;$('spaceSelect').innerHTML=spaces.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');if(spaces.some(s=>s.id===selected))$('spaceSelect').value=selected;}
function selectedSpace(){return(state?.spaces||[]).find(s=>s.id===$('spaceSelect').value)}
function openSpace(s){$('spaceId').value=s?.id||'';$('spaceName').value=s?.name||'';$('spaceDescription').value=s?.description||'';$('spaceBasePath').value=s?.basePath||'';$('spacePolicy').value=s?.policy||'';$('spaceModal').classList.add('show')}
function closeSpace(){$('spaceModal').classList.remove('show')}
$('editSpaceBtn').onclick=()=>openSpace(selectedSpace());$('closeSpaceModal').onclick=$('cancelSpaceBtn').onclick=closeSpace;$('saveSpaceBtn').onclick=async()=>{try{await post('/api/spaces',{id:$('spaceId').value||undefined,name:$('spaceName').value,description:$('spaceDescription').value,basePath:$('spaceBasePath').value,policy:$('spacePolicy').value});closeSpace();await refreshSystem();toast('Contexto salvo.')}catch(e){toast(e.message)}};
$('pickFileBtn').onclick=async()=>{setBusy('pickFileBtn',true,'Abrindo…');try{const j=await post('/api/pick/file');if(j.path)$('docPath').value=j.path;else toast('Nenhum documento selecionado.')}catch(e){toast(e.message)}finally{setBusy('pickFileBtn',false,'Escolher arquivo')}};
$('readDocBtn').onclick=async()=>{const p=$('docPath').value.trim();if(!p)return toast('Escolha um documento.');setBusy('readDocBtn',true,'Lendo documento inteiro…');try{const d=(await post('/api/document/read',{path:p})).document;currentDocText=d.text||'';$('docTitle').textContent=d.name;$('docText').textContent=d.text||d.warning||'Nenhum texto extraído.';$('docMeta').className='doc-meta';$('docMeta').innerHTML=`<dl><dt>Formato</dt><dd>${esc(d.ext)}</dd><dt>Tamanho</dt><dd>${fmtBytes(d.size)}</dd><dt>Método</dt><dd>${esc(d.method)}</dd><dt>SHA-256</dt><dd><code>${esc(d.sha256)}</code></dd><dt>Texto</dt><dd>${d.textLength.toLocaleString('pt-BR')} caracteres</dd><dt>Leitura</dt><dd>${d.complete?'Integral ✓':'Parcial'}</dd><dt>Integridade</dt><dd>Original intocado ✓</dd></dl>${d.warning?`<p class="warning">${esc(d.warning)}</p>`:''}`;$('copyDocBtn').disabled=!currentDocText;toast('Documento lido integralmente em modo somente leitura.')}catch(e){toast(e.message)}finally{setBusy('readDocBtn',false,'Ler documento inteiro')}};$('copyDocBtn').onclick=async()=>{await navigator.clipboard.writeText(currentDocText);toast('Texto copiado.')};
function renderTransactions(){if(!state)return;const txs=state.transactions||[];$('transactions').innerHTML=txs.length?txs.map(t=>`<article class="transaction"><div class="transaction-head"><div><h3>${esc(t.status)} · ${t.summary?.completed||0}/${t.summary?.requested||t.operations?.length||0} concluídas</h3><small>${fmtDate(t.createdAt)} · ${esc(t.id)}</small></div>${!['rolled_back'].includes(t.status)?`<button class="ghost rollback" data-id="${esc(t.id)}">Desfazer transação</button>`:'<span class="status ok">desfeita</span>'}</div><div class="transaction-ops">${(t.operations||[]).map(o=>`<div class="transaction-op"><b>${esc(o.type)}</b> · ${esc(o.before)} → ${esc(o.after||o.requestedAfter||'')} ${o.error?`<br><span class="warning">${esc(o.error)}</span>`:''}</div>`).join('')}</div></article>`).join(''):'<div class="empty-state">Ainda não há operações executadas.</div>';document.querySelectorAll('.rollback').forEach(b=>b.onclick=()=>rollback(b.dataset.id));}
async function rollback(id){if(!confirm('Desfazer esta transação? O Workspace não sobrescreverá arquivos que tenham ocupado o caminho original.'))return;try{await post(`/api/transactions/${id}/rollback`);await refreshSystem();toast('Rollback processado.')}catch(e){toast(e.message)}}
async function boot(){await refreshSystem();initFileOrganizer({go,refreshSystem});initV17Enhancements();initQuarantineHotfix();initProjects({onCount:n=>$('metricProjects').textContent=n});}
boot().catch(e=>toast(e.message));
