import {api,post,esc,fmtBytes,toast} from './common.js';

function ensureRecoveryUi(){
  if(document.getElementById('recovery'))return;
  const historyNav=document.querySelector('.nav[data-section="history"]');
  const b=document.createElement('button');b.className='nav';b.dataset.section='recovery';b.innerHTML='<span>⛨</span> Recuperação';
  if(historyNav)historyNav.before(b);else document.querySelector('aside')?.appendChild(b);
  const host=document.querySelector('main')||document.body;
  const section=document.createElement('section');section.id='recovery';section.className='page';section.innerHTML=`
    <div class="page-head"><div><span class="kicker">SAFETY CENTER</span><h2>Centro de Recuperação</h2><p>Audite movimentações antigas e restaure checkpoints físicos independentes do histórico principal.</p></div><span class="status ok">modo seguro</span></div>
    <article class="panel recovery-warning"><b>Proteção ativa</b><p>Novas movimentações só começam depois que todos os arquivos selecionados forem copiados para um checkpoint físico verificável. Se o checkpoint falhar, nenhum arquivo é movido.</p></article>
    <div class="recovery-grid">
      <article class="panel"><div class="panel-head"><div><span class="kicker">AUDITORIA</span><h3>Onde estão os arquivos do histórico</h3></div><button class="secondary small" id="refreshRecoveryAudit">Atualizar</button></div><div id="recoveryAudit"><div class="empty-state">Carregando auditoria…</div></div></article>
      <article class="panel"><div class="panel-head"><div><span class="kicker">CHECKPOINTS</span><h3>Backups físicos</h3></div></div><div id="recoveryCheckpoints"><div class="empty-state">Carregando checkpoints…</div></div></article>
    </div>`;
  host.appendChild(section);
}
function metric(v,label){return `<div><strong>${Number(v||0).toLocaleString('pt-BR')}</strong><span>${esc(label)}</span></div>`}
async function loadAudit(){const box=document.getElementById('recoveryAudit');if(!box)return;box.innerHTML='<div class="empty-state">Auditando caminhos conhecidos…</div>';try{const a=await api('/api/recovery/audit'),s=a.audit.summary;box.innerHTML=`<div class="result-metrics">${metric(s.atOriginal,'já estão no caminho original')}${metric(s.atDestination,'ainda estão em destino organizado')}${metric(s.notInKnownPaths,'não estão nos caminhos históricos')}${metric(s.operations,'operações históricas')}</div><p class="result-copy">“Não estão nos caminhos históricos” não significa automaticamente perda: o mesmo arquivo pode ter participado de várias transações ou ter sido movido manualmente. Esses casos exigem busca por hash antes de qualquer conclusão.</p>`;}catch(e){box.innerHTML=`<div class="empty-state warning">${esc(e.message)}</div>`}}
async function restore(id,dryRun){try{const r=await post(`/api/recovery/checkpoints/${encodeURIComponent(id)}/restore`,{dryRun});const s=r.restore.summary;toast(dryRun?`Simulação: ${s.wouldRestore} poderiam ser restaurados.`:`Recuperação: ${s.restored} restaurados.`);await loadCheckpoints();}catch(e){toast(e.message)}}
async function loadCheckpoints(){const box=document.getElementById('recoveryCheckpoints');if(!box)return;try{const j=await api('/api/recovery/checkpoints'),items=j.checkpoints||[];box.innerHTML=items.length?items.map(c=>`<div class="recovery-checkpoint"><div><b>${esc(c.id)}</b><small>${new Date(c.createdAt).toLocaleString('pt-BR')} · ${c.totalFiles} arquivo(s) · ${fmtBytes(c.totalBytes||0)} · ${esc(c.status)}</small></div><div><button class="ghost tiny recovery-dry" data-id="${esc(c.id)}">Simular restauração</button><button class="secondary tiny recovery-apply" data-id="${esc(c.id)}">Restaurar ausentes</button></div></div>`).join(''):'<div class="empty-state">Ainda não existem checkpoints físicos. Eles serão criados automaticamente antes da próxima movimentação.</div>';document.querySelectorAll('.recovery-dry').forEach(x=>x.onclick=()=>restore(x.dataset.id,true));document.querySelectorAll('.recovery-apply').forEach(x=>x.onclick=()=>{if(confirm('Restaurar apenas arquivos cujo caminho original está ausente? Nada existente será sobrescrito.'))restore(x.dataset.id,false)});}catch(e){box.innerHTML=`<div class="empty-state warning">${esc(e.message)}</div>`}}
export function initRecoveryCenter({go}={}){ensureRecoveryUi();const nav=document.querySelector('.nav[data-section="recovery"]');if(nav)nav.onclick=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='recovery'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section==='recovery'));const t=document.getElementById('pageTitle');if(t)t.textContent='Recuperação';loadAudit();loadCheckpoints();};document.getElementById('refreshRecoveryAudit')?.addEventListener('click',loadAudit);const hero=document.querySelector('#overview .hero, #overview .overview-hero');if(hero&&!document.getElementById('safetyModeBanner')){const d=document.createElement('div');d.id='safetyModeBanner';d.className='protected-summary';d.innerHTML='<b>Modo seguro ativo</b><span>Antes de mover qualquer arquivo, o Workspace cria um checkpoint físico independente. Recuperação disponível no menu ⛨ Recuperação.</span>';hero.appendChild(d);} }
