import {api,post,esc,fmtBytes,toast} from './common.js';

const restoreStatusLabels={
  would_restore:'seria restaurado',restored:'restaurado',original_matches_checkpoint:'original igual ao checkpoint',original_changed:'original alterado depois do checkpoint',original_exists_unverified:'original existente sem validação',backup_missing:'backup ausente',backup_changed:'backup alterado',restore_integrity_failed:'falha de integridade na restauração'
};
const checkpointStatusLabels={ready:'pronto',creating:'criando',failed:'falhou',cancelled:'cancelado'};
function ensureRecoveryUi(){
  if(document.getElementById('recovery'))return;
  const historyNav=document.querySelector('.nav[data-section="history"]');
  const b=document.createElement('button');b.className='nav';b.dataset.section='recovery';b.innerHTML='<span>⛨</span> Recuperação';
  if(historyNav)historyNav.before(b);else document.querySelector('aside')?.appendChild(b);
  const host=document.querySelector('main')||document.body;
  const section=document.createElement('section');section.id='recovery';section.className='page';section.innerHTML=`
    <div class="page-head"><div><span class="kicker">SAFETY CENTER</span><h2>Centro de Recuperação</h2><p>Audite movimentações antigas e restaure checkpoints físicos independentes do histórico principal.</p></div><span class="status ok">modo seguro</span></div>
    <article class="panel recovery-warning"><b>Proteção ativa</b><p>Novas movimentações só começam depois que todos os arquivos selecionados forem copiados para um checkpoint físico verificável. Se o checkpoint falhar, nenhum arquivo é movido.</p></article>
    <div class="recovery-grid">
      <article class="panel"><div class="panel-head"><div><span class="kicker">AUDITORIA</span><h3>Onde estão os arquivos do histórico</h3></div><button class="secondary small" id="refreshRecoveryAudit">Atualizar</button></div><div id="recoveryAudit"><div class="empty-state">Carregando auditoria…</div></div></article>
      <article class="panel"><div class="panel-head"><div><span class="kicker">CHECKPOINTS</span><h3>Backups físicos</h3></div></div><div id="recoveryCheckpoints"><div class="empty-state">Carregando checkpoints…</div></div></article>
    </div>
    <article class="panel" id="recoveryReportPanel" hidden><div class="panel-head"><div><span class="kicker">VERIFICAÇÃO</span><h3 id="recoveryReportTitle">Resultado da simulação</h3></div><span class="status neutral" id="recoveryReportStatus">auditoria</span></div><div id="recoveryReport"></div></article>`;
  host.appendChild(section);
}
function metric(v,label){return `<div><strong>${Number(v||0).toLocaleString('pt-BR')}</strong><span>${esc(label)}</span></div>`}
function checkpointStatus(status){return checkpointStatusLabels[status]||status||'desconhecido'}
function restoreStatus(status){return restoreStatusLabels[status]||status||'desconhecido'}
async function loadAudit(){const box=document.getElementById('recoveryAudit');if(!box)return;box.innerHTML='<div class="empty-state">Auditando caminhos conhecidos…</div>';try{const a=await api('/api/recovery/audit'),s=a.audit.summary;box.innerHTML=`<div class="result-metrics">${metric(s.atOriginal,'já estão no caminho original')}${metric(s.atDestination,'ainda estão em destino organizado')}${metric(s.notInKnownPaths,'não estão nos caminhos históricos')}${metric(s.operations,'operações históricas')}</div><p class="result-copy">“Não estão nos caminhos históricos” não significa automaticamente perda: o mesmo arquivo pode ter participado de várias transações ou ter sido movido manualmente. Esses casos exigem busca por hash antes de qualquer conclusão.</p>`;}catch(e){box.innerHTML=`<div class="empty-state warning">${esc(e.message)}</div>`}}
function renderRestoreReport(r){const panel=document.getElementById('recoveryReportPanel'),box=document.getElementById('recoveryReport'),title=document.getElementById('recoveryReportTitle'),status=document.getElementById('recoveryReportStatus');if(!panel||!box)return;const s=r.summary||{},issues=(s.originalChanged||0)+(s.backupMissing||0)+(s.backupChanged||0)+(s.restoreIntegrityFailed||0)+(s.originalExistsUnverified||0);title.textContent=r.dryRun?'Resultado da simulação':'Resultado da restauração';status.className=`status ${issues?'warn':'ok'}`;status.textContent=issues?'revisar':'íntegro';box.innerHTML=`<div class="result-metrics">${metric(r.dryRun?s.wouldRestore:s.restored,r.dryRun?'seriam restaurados':'restaurados')}${metric(s.originalMatchesCheckpoint,'originais já íntegros')}${metric(s.originalChanged,'originais alterados')}${metric((s.backupMissing||0)+(s.backupChanged||0)+(s.restoreIntegrityFailed||0),'problemas de backup/hash')}</div><p class="result-copy">Nenhum original existente é sobrescrito silenciosamente. Backups divergentes do SHA-256 do checkpoint são bloqueados. A restauração copia o backup e mantém o checkpoint disponível.</p><div class="result-list">${(r.results||[]).slice(0,40).map(x=>`<div class="${['backup_missing','backup_changed','restore_integrity_failed','original_changed'].includes(x.status)?'failed':''}"><span>${['would_restore','restored','original_matches_checkpoint'].includes(x.status)?'✓':'!'}</span><code>${esc(x.original)} · ${esc(restoreStatus(x.status))}</code></div>`).join('')||'<div>Nenhum item no relatório.</div>'}</div>${(r.results||[]).length>40?`<p class="result-copy">Mostrando 40 de ${(r.results||[]).length} itens. Os totais acima consideram todo o checkpoint.</p>`:''}`;panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'});}
async function restore(id,dryRun){try{const r=await post(`/api/recovery/checkpoints/${encodeURIComponent(id)}/restore`,{dryRun});renderRestoreReport(r.restore);const s=r.restore.summary;toast(dryRun?`Simulação concluída: ${s.wouldRestore} poderiam ser restaurados.`:`Recuperação concluída: ${s.restored} restaurados.`);await loadCheckpoints();}catch(e){toast(e.message)}}
function checkpointRow(c){const ready=c.status==='ready',statusClass=ready?'ok':c.status==='creating'?'neutral':'warn',detail=c.error?`<small>${esc(c.error)}</small>`:'';return `<div class="recovery-checkpoint"><div><b>${esc(c.id)}</b><small>${new Date(c.createdAt).toLocaleString('pt-BR')} · ${c.totalFiles} arquivo(s) · ${fmtBytes(c.totalBytes||0)} · <span class="status ${statusClass}">${esc(checkpointStatus(c.status))}</span></small>${detail}</div><div>${ready?`<button class="ghost tiny recovery-dry" data-id="${esc(c.id)}">Simular restauração</button><button class="secondary tiny recovery-apply" data-id="${esc(c.id)}">Restaurar ausentes</button>`:`<span class="status ${statusClass}">${c.status==='creating'?'aguarde':'somente auditoria'}</span>`}</div></div>`;}
async function loadCheckpoints(){const box=document.getElementById('recoveryCheckpoints');if(!box)return;try{const j=await api('/api/recovery/checkpoints'),items=j.checkpoints||[];box.innerHTML=items.length?items.map(checkpointRow).join(''):'<div class="empty-state">Ainda não existem checkpoints físicos. Eles serão criados automaticamente antes da próxima movimentação.</div>';document.querySelectorAll('.recovery-dry').forEach(x=>x.onclick=()=>restore(x.dataset.id,true));document.querySelectorAll('.recovery-apply').forEach(x=>x.onclick=()=>{if(confirm('Restaurar apenas arquivos cujo caminho original está ausente? Nada existente será sobrescrito e o checkpoint continuará preservado.'))restore(x.dataset.id,false)});}catch(e){box.innerHTML=`<div class="empty-state warning">${esc(e.message)}</div>`}}
export function initRecoveryCenter({go}={}){ensureRecoveryUi();const nav=document.querySelector('.nav[data-section="recovery"]');if(nav)nav.onclick=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='recovery'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section==='recovery'));const t=document.getElementById('pageTitle');if(t)t.textContent='Recuperação';loadAudit();loadCheckpoints();};document.getElementById('refreshRecoveryAudit')?.addEventListener('click',loadAudit);const hero=document.querySelector('#overview .hero, #overview .overview-hero');if(hero&&!document.getElementById('safetyModeBanner')){const d=document.createElement('div');d.id='safetyModeBanner';d.className='protected-summary';d.innerHTML='<b>Modo seguro ativo</b><span>Antes de mover qualquer arquivo, o Workspace cria um checkpoint físico independente. Recuperação disponível no menu ⛨ Recuperação.</span>';hero.appendChild(d);} }
