import {$,api,post,toast,esc,fmtBytes,fmtDate,setBusy} from './common.js';

const cache=new Map();
const referenceExts=new Set(['.html','.htm','.url','.lnk']);
let activeId=null,lastPreflight=null;
function fileName(p=''){return String(p).split(/[\\/]/).filter(Boolean).pop()||p;}
function dirName(p=''){const s=String(p),i=Math.max(s.lastIndexOf('\\'),s.lastIndexOf('/'));return i>=0?s.slice(0,i):'';}
function extName(p=''){const n=fileName(p),i=n.lastIndexOf('.');return i>=0?n.slice(i).toLowerCase():'';}
function rowById(id){return[...document.querySelectorAll('.plan-row')].find(r=>r.querySelector('.op-check')?.value===id)||null;}
function checked(id,value){const c=rowById(id)?.querySelector('.op-check');if(!c)return;c.checked=value;c.dispatchEvent(new Event('change',{bubbles:true}));}
function ensureUi(){
  if($('reviewBackdrop'))return;
  document.body.insertAdjacentHTML('beforeend',`<div class="review-backdrop" id="reviewBackdrop" hidden><aside class="review-drawer" id="reviewDrawer" aria-label="Revisão do arquivo"><header><div><span class="kicker">REVISÃO DO ITEM</span><h2 id="reviewTitle">Arquivo</h2></div><button class="icon-btn" id="reviewClose" title="Fechar">×</button></header><div class="review-body" id="reviewBody"><div class="loading-box">Carregando…</div></div></aside></div>`);
  $('reviewClose').onclick=closeReview;$('reviewBackdrop').addEventListener('click',e=>{if(e.target===$('reviewBackdrop'))closeReview();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('reviewBackdrop').hidden)closeReview();});
}
function closeReview(){if($('reviewBackdrop'))$('reviewBackdrop').hidden=true;activeId=null;}
function riskBanner(info){if(!info.operation.referenceRisk)return'';return`<div class="reference-warning"><b>Referência externa protegida</b><span>Este tipo de arquivo pode estar salvo em favoritos, atalhos ou links locais. Se ele entrar na execução, o Workspace preservará os originais do lote automaticamente para manter o caminho antigo funcional.</span></div>`;}
function docBanner(info){const d=info.document;if(!d)return`<div class="review-doc-note">A prévia textual pode ser aberta abaixo quando o formato for suportado.</div>`;return`<div class="review-doc-card"><div><span>Conteúdo identificado</span><b>${esc(d.topic||d.bucket||d.area||'Documento')}</b></div><small>${esc(d.summary||`${d.textLength||0} caracteres extraídos${d.complete?' · leitura integral':''}`)}</small></div>`;}
function traceBlock(info){const t=info.trace||{},history=t.history||[];return`<details class="review-trace" ${t.edited?'open':''}><summary>Rastreabilidade do plano ${t.edited?`· ${history.length} ajuste(s)`:''}</summary><div><b>Sugestão original</b><code>${esc(t.original?.after||info.operation.after)}</code>${history.slice(-5).reverse().map(h=>`<small>${esc(fmtDate(h.at))} · ${esc(h.note||'ajuste')}<br>${esc(h.before?.after||'')} → ${esc(h.after?.after||'')}</small>`).join('')}</div></details>`;}
function renderReview(info){
  cache.set(info.operation.id,info);activeId=info.operation.id;$('reviewTitle').textContent=info.source.name||fileName(info.operation.before);const op=info.operation,src=info.source;
  $('reviewBody').innerHTML=`${riskBanner(info)}<section class="review-summary"><div class="review-tags"><span>${esc(op.area||'Outros')}</span><span>${esc(op.family||op.subject||'Geral')}</span><span>${esc(op.category||src.ext||'Arquivo')}</span>${info.trace?.edited?'<span class="edited">ajustado</span>':''}</div><p>${esc(op.reason||'Sugestão automática de organização')}</p>${docBanner(info)}</section><section class="review-paths"><label>Onde está agora<div class="path-box"><code>${esc(op.before)}</code><button class="icon-btn review-copy" data-copy="${esc(op.before)}" title="Copiar caminho">⧉</button><button class="icon-btn" id="reviewReveal" title="Mostrar no Explorador">⌖</button></div></label><label>Para onde irá<div class="path-box destination"><code>${esc(op.after)}</code><button class="icon-btn review-copy" data-copy="${esc(op.after)}" title="Copiar destino">⧉</button></div></label></section><section class="review-edit"><div class="review-section-head"><div><span class="kicker">AJUSTAR PROPOSTA</span><h3>Nome e pasta</h3></div><span>não move nada agora</span></div><label>Nome final<input id="reviewFilename" value="${esc(fileName(op.after))}"></label><label>Pasta de destino<div class="input-action"><input id="reviewDestination" value="${esc(dirName(op.after))}"><button class="secondary" id="reviewPickFolder">Escolher</button></div></label><div class="review-edit-actions"><button class="primary" id="reviewSave">Salvar ajuste</button><button class="ghost" id="reviewReset" ${info.trace?.original?'':'disabled'}>Voltar à sugestão</button><button class="ghost" id="reviewExclude">Não mover este item</button></div></section><section class="review-preview"><div class="review-section-head"><div><span class="kicker">CONTEÚDO</span><h3>Identifique antes de decidir</h3></div><button class="secondary small" id="reviewPreviewBtn">Ler documento</button></div><div id="reviewPreviewText" class="review-preview-empty">A leitura é somente leitura e não altera o original.</div></section>${traceBlock(info)}`;
  document.querySelectorAll('.review-copy').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy||'');toast('Caminho copiado.');});
  $('reviewReveal').onclick=()=>reveal(op.before);$('reviewPickFolder').onclick=pickDestination;$('reviewSave').onclick=saveReview;$('reviewReset').onclick=resetReview;$('reviewExclude').onclick=()=>{checked(op.id,false);toast('Item retirado da seleção. O arquivo não será movido.');closeReview();};$('reviewPreviewBtn').onclick=loadPreview;
}
async function openReview(id,preview=false){ensureUi();activeId=id;$('reviewBackdrop').hidden=false;$('reviewBody').innerHTML='<div class="loading-box"><span class="spinner"></span> Carregando item…</div>';try{const info=(await api(`/api/review/operations/${encodeURIComponent(id)}`)).review;renderReview(info);if(preview)await loadPreview();}catch(e){toast(e.message);$('reviewBody').innerHTML=`<div class="empty-state">${esc(e.message)}</div>`;}}
async function pickDestination(){setBusy('reviewPickFolder',true,'Abrindo…');try{const j=await post('/api/pick/folder');if(j.path)$('reviewDestination').value=j.path;}catch(e){toast(e.message)}finally{setBusy('reviewPickFolder',false,'Escolher')}}
async function saveReview(){if(!activeId)return;setBusy('reviewSave',true,'Salvando…');try{const j=await post(`/api/review/operations/${encodeURIComponent(activeId)}`,{filename:$('reviewFilename').value,destinationDir:$('reviewDestination').value,note:'Nome/pasta ajustados na revisão visual'}),info=await api(`/api/review/operations/${encodeURIComponent(activeId)}`);cache.set(activeId,info.review);patchRow(info.review.operation);renderReview(info.review);toast('Proposta atualizada. Nenhum arquivo foi movido.');}catch(e){toast(e.message)}finally{setBusy('reviewSave',false,'Salvar ajuste')}}
async function resetReview(){if(!activeId)return;setBusy('reviewReset',true,'Restaurando…');try{await post(`/api/review/operations/${encodeURIComponent(activeId)}/reset`);const info=(await api(`/api/review/operations/${encodeURIComponent(activeId)}`)).review;cache.set(activeId,info);patchRow(info.operation);renderReview(info);toast('Sugestão automática restaurada.');}catch(e){toast(e.message)}finally{setBusy('reviewReset',false,'Voltar à sugestão')}}
async function loadPreview(){if(!activeId)return;const info=cache.get(activeId),box=$('reviewPreviewText'),btn=$('reviewPreviewBtn');if(!info||!box)return;setBusy(btn,true,'Lendo…');box.className='review-preview-empty';box.textContent='Extraindo conteúdo em modo somente leitura…';try{const d=(await post('/api/document/read',{path:info.operation.before})).document;box.className='review-preview-text';box.innerHTML=`<div class="preview-meta"><span>${esc(d.ext||'')}</span><span>${fmtBytes(d.size||0)}</span><span>${d.complete?'leitura integral':'leitura parcial'}</span></div><pre>${esc((d.text||d.warning||'Nenhum texto extraído.').slice(0,18000))}</pre>${(d.text||'').length>18000?'<small>Prévia limitada a 18.000 caracteres. O arquivo original permanece intacto.</small>':''}`;}catch(e){box.className='review-preview-empty';box.innerHTML=`Não consegui gerar prévia textual deste formato. <button class="ghost tiny" id="previewRevealFallback">Mostrar arquivo no Explorador</button>`;$('previewRevealFallback').onclick=()=>reveal(info.operation.before);}finally{setBusy(btn,false,'Ler documento')}}
async function reveal(path){try{await post('/api/review/reveal',{path});toast('Arquivo localizado no Explorador.');}catch(e){toast(e.message)}}
function patchRow(op){const row=rowById(op.id);if(!row)return;const to=row.querySelector('code.to');if(to)to.textContent=op.after;row.classList.toggle('review-edited',Boolean(op.reviewEdited));let badge=row.querySelector('.review-edited-badge');if(op.reviewEdited&&!badge){badge=document.createElement('span');badge.className='review-edited-badge';badge.textContent='ajustado';row.querySelector('.review-row-title')?.appendChild(badge);}if(!op.reviewEdited&&badge)badge.remove();}
function addReviewToolbar(plan){if(!plan||plan.querySelector('.review-toolbar'))return;const master=plan.querySelector('.plan-master-toolbar');if(!master)return;master.insertAdjacentHTML('afterend',`<div class="review-toolbar"><div><b>Revise antes de aplicar</b><span>Clique em um arquivo para ler conteúdo, ajustar nome/pasta ou localizar o original. Ajustes alteram apenas o plano.</span></div><div class="review-legend"><span>⌕ revisar</span><span>⌖ localizar</span><span class="reference">referência protegida</span></div></div>`);}
function decorateRows(){const plan=$('plan');if(!plan)return;addReviewToolbar(plan);plan.querySelectorAll('.plan-row').forEach(row=>{if(row.dataset.reviewReady)return;const check=row.querySelector('.op-check'),from=row.querySelector('code:not(.to)'),to=row.querySelector('code.to');if(!check||!from||!to)return;row.dataset.reviewReady='1';const id=check.value,name=fileName(from.textContent),ext=extName(from.textContent),meta=[...row.children].find(x=>x.tagName==='SPAN'&&!x.classList.contains('arrow')&&!x.classList.contains('confidence'));
    if(meta){const h=document.createElement('div');h.className='review-row-title';h.innerHTML=`<strong>${esc(name)}</strong>`;meta.prepend(h);}
    if(referenceExts.has(ext)){row.classList.add('reference-risk');const badge=document.createElement('span');badge.className='reference-risk-badge';badge.textContent='referência protegida';row.querySelector('.review-row-title')?.appendChild(badge);if(check.checked&&!row.dataset.referenceDeselected){row.dataset.referenceDeselected='1';setTimeout(()=>checked(id,false),0);}}
    const actions=document.createElement('div');actions.className='review-row-actions';actions.innerHTML=`<button class="ghost tiny" data-act="review">⌕ Revisar</button><button class="ghost tiny" data-act="preview">▤ Ler</button><button class="ghost tiny" data-act="reveal">⌖ Localizar</button><button class="ghost tiny" data-act="exclude">○ Não mover</button>`;actions.onclick=e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();e.stopPropagation();if(b.dataset.act==='review')openReview(id);if(b.dataset.act==='preview')openReview(id,true);if(b.dataset.act==='reveal')reveal(from.textContent);if(b.dataset.act==='exclude'){checked(id,false);toast('Item retirado da seleção.');}};row.appendChild(actions);row.addEventListener('dblclick',e=>{if(!e.target.closest('button,input'))openReview(id);});
    const cached=cache.get(id);if(cached)patchRow(cached.operation);
  });}
function decoratePreflight(){const box=$('executionPreflight');if(!box||box.hidden||!lastPreflight?.referenceProtection?.required)return;if(box.querySelector('.reference-preflight'))return;const r=lastPreflight.referenceProtection,summary=box.querySelector('.protected-summary');summary?.insertAdjacentHTML('afterend',`<div class="reference-preflight"><b>${r.count} item(ns) com referência externa</b><span>O modo conservador será obrigatório nesta execução: os originais serão mantidos para não quebrar favoritos, atalhos ou links locais.</span></div>`);const keep=$('preserveOriginals');if(keep){keep.checked=true;keep.disabled=true;keep.closest('label')?.classList.add('forced-retention');}}
function decorateHistory(){document.querySelectorAll('#transactions .transaction').forEach(card=>{if(card.dataset.traceReady)return;card.dataset.traceReady='1';card.classList.add('traceable-transaction');const head=card.querySelector('.transaction-head>div');head?.insertAdjacentHTML('beforeend','<span class="trace-badge">origem → destino rastreável</span>');card.querySelectorAll('.transaction-op').forEach(op=>{op.title='Este registro mantém a origem e o destino da operação para auditoria.';});});}
function observe(){const mo=new MutationObserver(()=>{decorateRows();decoratePreflight();decorateHistory();});mo.observe(document.body,{childList:true,subtree:true});decorateRows();decorateHistory();}
export function initReviewExperience(){ensureUi();document.addEventListener('rbwi:api-response',e=>{const d=e.detail||{};if(d.url==='/api/execution/preflight'&&d.data?.preflight){lastPreflight=d.data.preflight;setTimeout(decoratePreflight,0);}});observe();}
