import { mkdir, rename, stat, access } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { id, readState, saveTransaction, updateTransaction } from './storage.mjs';
import { assertAllowedPath } from './workspace.mjs';

const jobs=new Map();
const CHECKPOINT_EVERY=50;
function now(){return new Date().toISOString();}
async function exists(p){try{await access(p);return true}catch{return false}}
async function hashFile(file){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256'),s=createReadStream(file);s.on('data',d=>h.update(d));s.on('error',reject);s.on('end',()=>resolve(h.digest('hex')));});}
function collisionSafe(target){const p=path.parse(target);return{dir:p.dir,base:p.name,ext:p.ext};}
async function uniqueTarget(target){if(!(await exists(target)))return target;const{dir,base,ext}=collisionSafe(target);for(let i=2;i<1000;i++){const candidate=path.join(dir,`${base} (${i})${ext}`);if(!(await exists(candidate)))return candidate;}throw new Error(`Não foi possível resolver colisão de nome em ${target}`);}
function publicJob(j){if(!j)return null;return{id:j.id,status:j.status,phase:j.phase,percent:j.percent,message:j.message,planId:j.planId,startedAt:j.startedAt,updatedAt:j.updatedAt,finishedAt:j.finishedAt||null,counters:{...j.counters},current:j.current||'',error:j.error||'',transaction:['completed','completed_with_errors','cancelled'].includes(j.status)?j.transaction:undefined};}
function setJob(j,patch){Object.assign(j,patch,{updatedAt:now()});}
async function checkpoint(tx){await updateTransaction(tx.id,{status:'running',operations:[...tx.operations],summary:{...tx.summary},lastCheckpointAt:now()});}
async function executeOne(op){const record={id:op.id,type:op.type,before:op.before,requestedAfter:op.after,status:'pending'};try{const source=assertAllowedPath(op.before),sourceStat=await stat(source).catch(()=>null);if(!sourceStat?.isFile())throw new Error('Arquivo de origem não existe mais.');let target=assertAllowedPath(op.after);target=await uniqueTarget(target);await mkdir(path.dirname(target),{recursive:true});const beforeHash=await hashFile(source).catch(()=>null);await rename(source,target);const afterHash=await hashFile(target).catch(()=>null);if(beforeHash&&afterHash&&beforeHash!==afterHash)throw new Error('Falha de integridade após movimentação.');Object.assign(record,{after:target,beforeHash,afterHash,status:'completed',completedAt:now()});}catch(e){record.status='failed';record.error=e.message;}return record;}
async function run(j){let tx=null;try{const state=await readState(),plan=state.plans.find(p=>p.id===j.planId);if(!plan)throw new Error('Plano não encontrado. Faça uma nova análise.');const ids=new Set(j.operationIds||[]),selected=plan.operations.filter(o=>ids.has(o.id));if(!selected.length)throw new Error('Selecione ao menos uma operação.');j.counters.requested=selected.length;j.counters.remaining=selected.length;tx={id:id('tx'),planId:j.planId,spaceId:plan.spaceId,createdAt:now(),status:'running',operations:[],summary:{requested:selected.length,completed:0,failed:0}};j.transaction=tx;await saveTransaction(tx);setJob(j,{status:'running',phase:'moving',percent:1,message:`Preparando ${selected.length} movimentações…`});for(let i=0;i<selected.length;i++){if(j.cancelled)break;const op=selected[i];j.current=op.before;setJob(j,{message:`Movendo ${i+1}/${selected.length} · ${path.basename(op.before)}`});const record=await executeOne(op);tx.operations.push(record);if(record.status==='completed')tx.summary.completed++;else tx.summary.failed++;const processed=i+1;j.counters.processed=processed;j.counters.completed=tx.summary.completed;j.counters.failed=tx.summary.failed;j.counters.remaining=Math.max(0,selected.length-processed);setJob(j,{percent:Math.max(1,Math.floor(processed/selected.length*100)),message:`${processed}/${selected.length} processadas · ${tx.summary.completed} movidas · ${tx.summary.failed} falharam`});if(processed%CHECKPOINT_EVERY===0)await checkpoint(tx);await new Promise(r=>setImmediate(r));}
  const wasCancelled=j.cancelled===true;tx.status=wasCancelled?'cancelled':tx.summary.failed?'completed_with_errors':'completed';tx.completedAt=now();await updateTransaction(tx.id,{status:tx.status,operations:[...tx.operations],summary:{...tx.summary},completedAt:tx.completedAt});j.transaction=tx;setJob(j,{status:tx.status,phase:wasCancelled?'cancelled':'done',percent:wasCancelled?j.percent:100,message:wasCancelled?`Execução cancelada · ${tx.summary.completed} arquivos movidos · ${tx.summary.failed} falharam`:`Execução concluída · ${tx.summary.completed} arquivos movidos · ${tx.summary.failed} falharam`,finishedAt:now(),current:''});
}catch(e){if(tx){tx.status='failed';tx.completedAt=now();try{await updateTransaction(tx.id,{status:'failed',operations:[...tx.operations],summary:{...tx.summary},completedAt:tx.completedAt,error:e.message})}catch{}}setJob(j,{status:'failed',phase:'failed',message:'A execução encontrou um erro.',error:e.message,finishedAt:now(),current:''});}}
function trimJobs(){const finished=[...jobs.values()].filter(j=>!['queued','running'].includes(j.status)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));for(const j of finished.slice(20))jobs.delete(j.id);}
export function startExecutionJob({planId,operationIds}){const active=[...jobs.values()].find(j=>['queued','running'].includes(j.status));if(active)throw new Error('Já existe uma execução em andamento. Aguarde ou cancele antes de iniciar outra.');const j={id:id('execjob'),planId,operationIds:[...(operationIds||[])],status:'queued',phase:'queued',percent:0,message:'Preparando execução…',startedAt:now(),updatedAt:now(),finishedAt:null,counters:{requested:(operationIds||[]).length,processed:0,completed:0,failed:0,remaining:(operationIds||[]).length},current:'',cancelled:false,transaction:null,error:''};jobs.set(j.id,j);trimJobs();run(j);return publicJob(j);}
export function executionJobStatus(jobId){const j=jobs.get(jobId);if(!j)throw new Error('Execução não encontrada ou já expirada.');return publicJob(j);}
export function cancelExecutionJob(jobId){const j=jobs.get(jobId);if(!j)throw new Error('Execução não encontrada.');if(!['queued','running'].includes(j.status))return publicJob(j);j.cancelled=true;setJob(j,{message:'Cancelamento solicitado. Finalizando o arquivo atual…'});return publicJob(j);}
