import { readFile, stat, mkdir, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readState, registerProject } from './storage.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const projectsRoot=process.env.RB_PROJECTS_DIR||path.join(os.homedir(),'RB','Projects');
const registryFile=path.join(root,'projects.registry.json');
const ignored=new Set(['.git','node_modules','.next','dist','build','.venv','venv','__pycache__','.idea','.vscode','coverage','target','bin','obj']);

function commandExists(name){const r=spawnSync(process.platform==='win32'?'where.exe':'which',[name],{encoding:'utf8',windowsHide:true});return r.status===0;}
function run(command,cwd,{detached=false}={}){if(detached){if(process.platform==='win32'){const child=spawn('cmd.exe',['/d','/s','/c',`start "RB Project" cmd /k ${command}`],{cwd,detached:true,stdio:'ignore',windowsHide:true});child.on('error',()=>{});child.unref();return{status:0,stdout:'Processo iniciado em uma janela própria.',stderr:''};}const child=spawn('sh',['-lc',command],{cwd,detached:true,stdio:'ignore'});child.on('error',()=>{});child.unref();return{status:0,stdout:`Processo iniciado · PID ${child.pid}`,stderr:''};}return process.platform==='win32'?spawnSync('cmd.exe',['/d','/s','/c',command],{cwd,encoding:'utf8',maxBuffer:16*1024*1024,windowsHide:true}):spawnSync('sh',['-lc',command],{cwd,encoding:'utf8',maxBuffer:16*1024*1024});}
function git(args,cwd){return spawnSync('git',args,{cwd,encoding:'utf8',maxBuffer:16*1024*1024,windowsHide:true});}
function cursorExe(){if(process.platform!=='win32')return null;const b=process.env.LOCALAPPDATA||'';return[path.join(b,'Programs','cursor','Cursor.exe'),path.join(b,'Programs','Cursor','Cursor.exe')].find(existsSync)||null;}
function codeExe(){if(process.platform!=='win32')return null;const b=process.env.LOCALAPPDATA||'';return[path.join(b,'Programs','Microsoft VS Code','Code.exe')].find(existsSync)||null;}
function openExternal(cmd,cwd){const r=process.platform==='win32'?spawnSync('cmd.exe',['/d','/s','/c',`start "" ${cmd}`],{cwd,encoding:'utf8',windowsHide:true}):spawnSync('sh',['-lc',cmd],{cwd,encoding:'utf8'});if(r.status)throw new Error(r.stderr||r.stdout||'Falha ao abrir aplicativo.');}
async function exists(p){try{await stat(p);return true}catch{return false}}
function slug(v){return String(v||'projeto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\.git$/i,'').replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||`project-${Date.now()}`;}
function safeLocal(input){const resolved=path.resolve(String(input||'')),home=path.resolve(os.homedir());const rel=path.relative(home,resolved);if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('Projetos locais devem ficar dentro do seu perfil de usuário.');return resolved;}
function validRepo(url){const u=String(url||'').trim();if(!u)throw new Error('Informe a URL do repositório.');if(!/^(https?:\/\/|ssh:\/\/|git@)[^\s]+$/i.test(u))throw new Error('Use uma URL Git válida.');return u;}
function repoId(url){const clean=String(url).replace(/[?#].*$/,'').replace(/\/$/,'');return slug(clean.split(/[/:]/).pop()||'project');}

async function registry(){let built=[];try{built=JSON.parse(await readFile(registryFile,'utf8')).projects||[]}catch{}const state=await readState(),discovered=[];await mkdir(projectsRoot,{recursive:true});for(const e of await readdir(projectsRoot,{withFileTypes:true}).catch(()=>[])){if(e.isDirectory()&&await exists(path.join(projectsRoot,e.name,'.git')))discovered.push({id:slug(e.name),name:e.name,directory:e.name,role:'independent-app',discovered:true});}const out=[];for(const p of [...built,...discovered,...(state.customProjects||[])]){const i=out.findIndex(x=>x.id===p.id||((x.localPath&&p.localPath)&&path.resolve(x.localPath)===path.resolve(p.localPath)));if(i>=0)out[i]={...out[i],...p};else out.push(p);}return out;}
function projectDir(p){if(p.id==='rb-workspace-intelligence')return root;if(p.localPath)return safeLocal(p.localPath);return path.join(projectsRoot,p.directory||p.id);}
function snapshot(cwd){if(!existsSync(path.join(cwd,'.git')))return{isGit:false,branch:'',hash:'',message:'',status:'',remote:'',dirty:false,ahead:0,behind:0};const branch=git(['branch','--show-current'],cwd),hash=git(['rev-parse','--short','HEAD'],cwd),msg=git(['log','-1','--pretty=%s'],cwd),status=git(['status','--short','--branch'],cwd),remote=git(['remote','get-url','origin'],cwd),counts=git(['rev-list','--left-right','--count','HEAD...@{upstream}'],cwd);let ahead=0,behind=0;if(counts.status===0){const [a,b]=(counts.stdout||'0 0').trim().split(/\s+/).map(Number);ahead=a||0;behind=b||0;}const text=(status.stdout||'').trim();return{isGit:true,branch:(branch.stdout||'').trim(),hash:(hash.stdout||'').trim(),message:(msg.stdout||'').trim(),status:text,remote:(remote.stdout||'').trim(),dirty:text.split('\n').slice(1).some(Boolean),ahead,behind};}
async function tree(dir,max=500){const entries=[];let truncated=false;async function walk(cur,rel='',depth=0){if(depth>4||entries.length>=max){truncated=true;return;}for(const e of (await readdir(cur,{withFileTypes:true}).catch(()=>[])).sort((a,b)=>a.name.localeCompare(b.name))){if(ignored.has(e.name))continue;const r=rel?`${rel}/${e.name}`:e.name;entries.push({path:r,type:e.isDirectory()?'dir':'file',depth});if(entries.length>=max){truncated=true;return;}if(e.isDirectory())await walk(path.join(cur,e.name),r,depth+1);}}await walk(dir);return{entries,truncated};}
async function readJson(file){try{return JSON.parse(await readFile(file,'utf8'))}catch{return null}}

async function detect(dir){const top=await readdir(dir,{withFileTypes:true}).catch(()=>[]),names=new Set(top.map(x=>x.name)),pkg=names.has('package.json')?await readJson(path.join(dir,'package.json')):null,rb=names.has('rb-project.json')?await readJson(path.join(dir,'rb-project.json')):null;const r={stack:'Desconhecida',frameworks:[],commands:{install:null,build:null,dev:null,start:null},localUrl:'',scripts:{},signals:[],recommendations:[],packageManager:null};
  if(pkg){const deps={...(pkg.dependencies||{}),...(pkg.devDependencies||{})},pm=names.has('pnpm-lock.yaml')?'pnpm':names.has('yarn.lock')?'yarn':(names.has('bun.lockb')||names.has('bun.lock'))?'bun':'npm',script=n=>pm==='npm'?`npm run ${n}`:pm==='yarn'?`yarn ${n}`:pm==='pnpm'?`pnpm ${n}`:`bun run ${n}`;r.stack='Node.js';r.scripts=pkg.scripts||{};r.packageManager=pm;r.commands.install=pm==='npm'?'npm install':`${pm} install`;if(pkg.scripts?.build)r.commands.build=script('build');if(pkg.scripts?.dev)r.commands.dev=script('dev');else if(pkg.scripts?.start)r.commands.start=pm==='npm'?'npm start':script('start');if(deps.next){r.stack='Next.js';r.frameworks.push('React','Next.js');r.localUrl='http://127.0.0.1:3000';}else if(deps.vite){r.stack='Vite';if(deps.react||deps['@vitejs/plugin-react'])r.frameworks.push('React');if(deps.vue)r.frameworks.push('Vue');if(deps.svelte)r.frameworks.push('Svelte');r.localUrl='http://127.0.0.1:5173';}else if(deps.react){r.stack='React';r.frameworks.push('React');r.localUrl='http://127.0.0.1:3000';}else if(deps.vue){r.stack='Vue';r.frameworks.push('Vue');r.localUrl='http://127.0.0.1:5173';}else if(deps.express){r.stack='Node.js / Express';r.frameworks.push('Express');r.localUrl='http://127.0.0.1:3000';}r.signals.push('package.json');}
  if(names.has('requirements.txt')||names.has('pyproject.toml')||names.has('Pipfile')){if(!pkg)r.stack='Python';r.frameworks.push('Python');r.commands.install=names.has('requirements.txt')?'python -m pip install -r requirements.txt':r.commands.install;let req='';if(names.has('requirements.txt'))req=(await readFile(path.join(dir,'requirements.txt'),'utf8').catch(()=>'' )).toLowerCase();if(req.includes('fastapi')||req.includes('uvicorn')){r.stack='Python / FastAPI';r.frameworks.push('FastAPI');r.commands.dev=`python -m uvicorn ${names.has('main.py')?'main':'app'}:app --reload`;r.localUrl='http://127.0.0.1:8000';}else if(req.includes('flask')){r.stack='Python / Flask';r.frameworks.push('Flask');const f=names.has('app.py')?'app.py':names.has('main.py')?'main.py':'';if(f)r.commands.dev=`python -m flask --app ${f} run`;r.localUrl='http://127.0.0.1:5000';}else if(req.includes('streamlit')){r.stack='Python / Streamlit';r.frameworks.push('Streamlit');const f=names.has('app.py')?'app.py':names.has('main.py')?'main.py':'';if(f)r.commands.dev=`python -m streamlit run ${f}`;r.localUrl='http://127.0.0.1:8501';}else if(names.has('main.py'))r.commands.dev='python main.py';else if(names.has('app.py'))r.commands.dev='python app.py';r.signals.push(names.has('pyproject.toml')?'pyproject.toml':'requirements.txt');}
  const cs=top.find(x=>x.isFile()&&(x.name.endsWith('.sln')||x.name.endsWith('.csproj')));if(cs&&!pkg){r.stack='.NET';r.frameworks.push('.NET');r.commands.install='dotnet restore';r.commands.build='dotnet build';r.commands.dev='dotnet run';r.localUrl='http://127.0.0.1:5000';r.signals.push(cs.name);}
  if(names.has('pom.xml')&&!pkg){r.stack='Java / Maven';r.frameworks.push('Java','Maven');r.commands.install='mvn dependency:resolve';r.commands.build='mvn package';const pom=(await readFile(path.join(dir,'pom.xml'),'utf8').catch(()=>'' )).toLowerCase();if(pom.includes('spring-boot')){r.commands.dev='mvn spring-boot:run';r.localUrl='http://127.0.0.1:8080';}r.signals.push('pom.xml');}
  const gradle=names.has('build.gradle')?'build.gradle':names.has('build.gradle.kts')?'build.gradle.kts':'';if(gradle&&!pkg){r.stack='Java / Gradle';r.frameworks.push('Java','Gradle');r.commands.build=process.platform==='win32'?'gradlew.bat build':'./gradlew build';const text=(await readFile(path.join(dir,gradle),'utf8').catch(()=>'' )).toLowerCase();if(text.includes('spring')||text.includes('bootrun')){r.commands.dev=process.platform==='win32'?'gradlew.bat bootRun':'./gradlew bootRun';r.localUrl='http://127.0.0.1:8080';}r.signals.push(gradle);}
  if(names.has('index.html')&&!pkg&&r.stack==='Desconhecida'){r.stack='HTML estático';r.frameworks.push('HTML/CSS/JS');r.commands.dev='python -m http.server 4321';r.localUrl='http://127.0.0.1:4321';r.signals.push('index.html');}
  if(rb){r.stack=rb.type||r.stack;r.commands={...r.commands,install:rb.install??r.commands.install,build:rb.build??r.commands.build,dev:rb.dev??r.commands.dev,start:rb.start??r.commands.start};r.localUrl=rb.localUrl||r.localUrl;r.signals.push('rb-project.json');}
  if(!r.commands.install)r.recommendations.push('Nenhuma etapa de dependências foi detectada.');if(!r.commands.build)r.recommendations.push('Nenhum build explícito foi detectado.');if(!r.commands.dev&&!r.commands.start)r.recommendations.push('Não foi possível inferir um comando de execução com segurança.');return r;}

export async function inspectLocalProject(id){const p=(await registry()).find(x=>x.id===id);if(!p)throw new Error('Projeto não encontrado.');const dir=projectDir(p);if(!(await exists(dir)))return{...p,path:dir,exists:false};const info=await detect(dir),files=await tree(dir),g=snapshot(dir);return{...p,path:dir,exists:true,name:p.name||path.basename(dir),...info,git:g,tree:files,stats:{files:files.entries.filter(x=>x.type==='file').length,folders:files.entries.filter(x=>x.type==='dir').length}};}
export async function listLocalProjects(){const projects=[];for(const p of await registry()){try{const x=await inspectLocalProject(p.id);projects.push({id:x.id,name:x.name,path:x.path,repository:x.repository||x.git?.remote||'',exists:x.exists,stack:x.stack,frameworks:x.frameworks,localUrl:x.localUrl,git:x.git,commands:x.commands,current:x.id==='rb-workspace-intelligence'});}catch{}}const cursor=commandExists('cursor')||!!cursorExe(),vscode=commandExists('code')||!!codeExe();return{projectsRoot,preferredEditor:cursor?'cursor':vscode?'vscode':null,tools:{git:commandExists('git'),node:commandExists('node'),python:commandExists('python'),cursor,vscode},projects};}
export async function cloneLocalProject(url){const repository=validRepo(url),id=repoId(repository),dir=path.join(projectsRoot,id);await mkdir(projectsRoot,{recursive:true});if(await exists(path.join(dir,'.git'))){await registerProject({id,name:id,repository,directory:id});return inspectLocalProject(id);}if(await exists(dir))throw new Error(`Já existe uma pasta chamada ${id}. Use “Escolher pasta local”.`);const r=git(['clone',repository,dir],projectsRoot);if(r.status)throw new Error(r.stderr||r.stdout||'git clone falhou. Verifique URL e autenticação.');await registerProject({id,name:id,repository,directory:id});return inspectLocalProject(id);}
export async function addExistingProject(localPath){const dir=safeLocal(localPath),s=await stat(dir).catch(()=>null);if(!s?.isDirectory())throw new Error('Selecione uma pasta válida.');const base=slug(path.basename(dir)),all=await registry();let id=base;if(all.some(p=>p.id===id&&projectDir(p)!==dir))id=`${base}-${Date.now().toString(36).slice(-4)}`;const g=snapshot(dir);await registerProject({id,name:path.basename(dir),repository:g.remote||'',localPath:dir,directory:''});return inspectLocalProject(id);}
export async function createEmptyProject(name){const clean=String(name||'').trim();if(!clean)throw new Error('Informe um nome.');const id=slug(clean),dir=path.join(projectsRoot,id);if(await exists(dir))throw new Error('Já existe uma pasta com este nome.');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'README.md'),`# ${clean}\n\nProjeto local criado pelo RB Workspace Intelligence.\n`,'utf8');const r=git(['init'],dir);if(r.status)throw new Error(r.stderr||'git init falhou');await registerProject({id,name:clean,directory:id,repository:''});return inspectLocalProject(id);}

export async function localProjectAction(id,action){const p=(await registry()).find(x=>x.id===id);if(!p)throw new Error('Projeto não encontrado.');const dir=projectDir(p);if(!(await exists(dir)))throw new Error('Projeto não está disponível localmente.');const info=await inspectLocalProject(id);if(action==='cursor'){if(commandExists('cursor')){openExternal(`cursor -n "${dir}"`,dir);return'Projeto aberto no Cursor.';}const exe=cursorExe();if(exe){openExternal(`"${exe}" -n "${dir}"`,dir);return'Projeto aberto no Cursor.';}throw new Error('Cursor não encontrado.');}if(action==='vscode'){if(commandExists('code')){openExternal(`code -n "${dir}"`,dir);return'Projeto aberto no VS Code.';}const exe=codeExe();if(exe){openExternal(`"${exe}" -n "${dir}"`,dir);return'Projeto aberto no VS Code.';}throw new Error('VS Code não encontrado.');}if(action==='install'){if(!info.commands.install)return'Nenhuma etapa de dependências foi inferida.';const r=run(info.commands.install,dir);if(r.status)throw new Error(r.stderr||r.stdout);return(r.stdout||'Dependências preparadas.').trim();}if(action==='build'){if(!info.commands.build)return'Nenhum build foi inferido.';const r=run(info.commands.build,dir);if(r.status)throw new Error(r.stderr||r.stdout);return(r.stdout||'Build concluído.').trim();}if(action==='run'){if(id==='rb-workspace-intelligence')return'O Workspace Intelligence já está executando.';const cmd=info.commands.dev||info.commands.start;if(!cmd)throw new Error('Não foi possível inferir um comando de execução com segurança.');return run(cmd,dir,{detached:true}).stdout;}if(action==='browser'){if(!info.localUrl)throw new Error('URL local não detectada.');openExternal(`"${info.localUrl}"`,dir);return`Aberto: ${info.localUrl}`;}throw new Error('Ação desconhecida.');}
export async function localGit(id,action,{message='',repository=''}={}){const p=(await registry()).find(x=>x.id===id);if(!p)throw new Error('Projeto não encontrado.');const dir=projectDir(p);let r;if(action==='init'){r=git(['init'],dir);if(r.status)throw new Error(r.stderr||'git init falhou');return{output:(r.stdout||r.stderr||'').trim(),snapshot:snapshot(dir)};}if(!(await exists(path.join(dir,'.git'))))throw new Error('Esta pasta ainda não é um repositório Git.');if(action==='status')return{snapshot:snapshot(dir)};if(action==='pull')r=git(['pull','--ff-only'],dir);else if(action==='fetch')r=git(['fetch'],dir);else if(action==='stage')r=git(['add','-A'],dir);else if(action==='unstage')r=git(['reset'],dir);else if(action==='commit'){const msg=String(message).trim();if(!msg)throw new Error('Escreva a mensagem do commit.');r=git(['commit','-m',msg],dir);}else if(action==='push'){r=git(['push'],dir);if(r.status){const s=snapshot(dir);if(!s.remote)throw new Error('Conecte um remote antes do push.');if(!s.branch)throw new Error('Branch atual não identificada.');r=git(['push','-u','origin',s.branch],dir);}}else if(action==='set-remote'){const remote=validRepo(repository),has=git(['remote','get-url','origin'],dir);r=has.status===0?git(['remote','set-url','origin',remote],dir):git(['remote','add','origin',remote],dir);if(!r.status)await registerProject({...p,repository:remote,localPath:p.localPath||'',directory:p.directory||''});}else throw new Error('Ação Git não permitida.');if(r.status)throw new Error(r.stderr||r.stdout||`Git ${action} falhou.`);return{output:(r.stdout||r.stderr||'').trim(),snapshot:snapshot(dir)};}
const basic=[/^git status(?: --short(?: --branch)?)?$/, /^git pull(?: --ff-only)?$/, /^git fetch(?: origin(?: main)?)?$/, /^git log(?: --oneline)?(?: -n \d{1,2})?$/, /^git diff(?: --stat)?$/, /^git branch(?: --show-current)?$/, /^git remote -v$/];
export async function localConsole(id,command){const info=await inspectLocalProject(id);if(!info.exists)throw new Error('Projeto não disponível.');const c=String(command||'').trim().replace(/\s+/g,' '),extra=Object.values(info.commands||{}).filter(Boolean);if(!basic.some(r=>r.test(c))&&!extra.includes(c))throw new Error('Comando não liberado. Use os comandos Git exibidos ou os comandos inferidos do projeto.');const r=run(c,info.path,{detached:c===(info.commands.dev||info.commands.start)});return{command:c,cwd:info.path,explanation:extra.includes(c)?'Comando inferido a partir da estrutura deste projeto.':'Comando Git guiado e não destrutivo.',status:r.status,ok:r.status===0,stdout:(r.stdout||'').trim(),stderr:(r.stderr||'').trim(),snapshot:snapshot(info.path)};}
