import { mkdir, readdir, stat, access } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { id, readState, savePlan, saveScan } from './storage.mjs';

const home=path.resolve(os.homedir());
const protectedRoots=process.platform==='win32'?['C:\\Windows','C:\\Program Files','C:\\Program Files (x86)','C:\\ProgramData']:['/bin','/sbin','/usr','/etc','/System'];
const ignoredNames=new Set(['.git','node_modules','$recycle.bin','appdata','.venv','venv','dist','build','.next','.cache','.bun','.npm','.pnpm-store','.yarn','.cargo','.rustup','.gradle','.m2','.nuget','.cursor','.vscode','.idea','coverage','target','bin','obj','__pycache__']);
const codeExts=new Set(['.js','.ts','.tsx','.jsx','.py','.java','.cs','.go','.rs','.php','.rb','.sql','.html','.css','.scss','.vue','.svelte']);
const categories={'.pdf':'PDFs','.doc':'Documentos','.docx':'Documentos','.odt':'Documentos','.txt':'Documentos','.md':'Documentos','.xlsx':'Planilhas','.xls':'Planilhas','.csv':'Planilhas','.ods':'Planilhas','.pptx':'Apresentações','.ppt':'Apresentações','.jpg':'Imagens','.jpeg':'Imagens','.png':'Imagens','.webp':'Imagens','.gif':'Imagens','.heic':'Imagens','.mp4':'Vídeos','.mov':'Vídeos','.mkv':'Vídeos','.avi':'Vídeos','.mp3':'Áudios','.wav':'Áudios','.zip':'Compactados','.rar':'Compactados','.7z':'Compactados','.json':'Dados','.xml':'Dados','.yaml':'Dados','.yml':'Dados','.js':'Código','.ts':'Código','.tsx':'Código','.jsx':'Código','.py':'Código','.java':'Código','.cs':'Código','.sql':'Código','.html':'Código','.css':'Código'};
const genericRoots=new Set(['downloads','download','desktop','área de trabalho','area de trabalho','documents','documentos','onedrive','pictures','imagens','videos','vídeos','music','música','musica']);
function norm(p){return path.resolve(String(p||''));}
function inside(base,target){const rel=path.relative(norm(base),norm(target));return rel===''||(!rel.startsWith('..')&&!path.isAbsolute(rel));}
export function assertAllowedPath(input){const resolved=norm(input);if(!input)throw new Error('Informe uma pasta ou arquivo.');if(!inside(home,resolved))throw new Error('Por segurança, o Workspace opera apenas dentro do seu perfil de usuário.');if(protectedRoots.some(p=>inside(p,resolved)||inside(resolved,p)))throw new Error('Esse caminho pertence a uma área protegida do sistema.');return resolved;}
async function exists(p){try{await access(p);return true}catch{return false}}
async function hashFile(file){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256');const s=createReadStream(file);s.on('data',d=>h.update(d));s.on('error',reject);s.on('end',()=>resolve(h.digest('hex')));});}
function extCategory(ext){return categories[ext]||'Outros';}
function sanitizeSegment(s){return String(s||'').replace(/[<>:"/\\|?*]+/g,' ').replace(/\s+/g,' ').trim().slice(0,80)||'Geral';}
function cleanFilename(name){const p=path.parse(name);let base=p.name;base=base.replace(/[_]+/g,' ').replace(/\s+/g,' ').trim();base=base.replace(/\s*[-_(]?\s*(c[oó]pia|copy|novo|final|final final|vers[aã]o final)\s*[)_-]?\s*$/i,'').trim();if(!base)base=p.name;return `${sanitizeSegment(base)}${p.ext.toLowerCase()}`;}
function poorName(name){const stem=path.parse(name).name;return /\b(final|novo|c[oó]pia|copy|documento|arquivo|sem t[ií]tulo)(?:\s*\d+)?\b/i.test(stem)||/_{2,}|\s{2,}|\(\d+\)$/.test(stem);}
function isTechnicalName(name){const n=String(name||'').toLowerCase();return ignoredNames.has(n)||n.startsWith('.')||/^cache$/i.test(n);}
async function isRepository(dir){return exists(path.join(dir,'.git'));}
function relParts(root,file){return path.relative(root,file).split(path.sep).filter(Boolean);}
function fold(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function inferArea(file,root,space){const rel=relParts(root,file.path),hay=fold(rel.join(' ')+' '+file.name),top=fold(rel[0]||'');if(/downloads?|desktop|area de trabalho/.test(top))return'Entrada';if(/picture|imagem|foto|video|music|musica/.test(top)||file.category==='Imagens'||file.category==='Vídeos'||file.category==='Áudios')return'Mídia pessoal';if(/finance|financeiro|extrato|boleto|fatura|darf|nota fiscal|pagamento|contabil|contábil/.test(hay))return'Financeiro';if(/condominio|condomínio|tower|sudene|avcb|elevador|manutencao|manutenção/.test(hay))return'Condomínio';if(/sefaz|maria|rb hub|rbhub|trabalho|cliente|empresa|contrato|relatorio|relatório|reuniao|reunião/.test(hay))return'Trabalho';if(/projeto|project|repo|repositorio|repositório|git|codigo|código|dev/.test(hay)||codeExts.has(file.ext))return'Projetos';if(/pessoal|familia|família|documentos pessoais|curriculo|currículo/.test(hay))return'Pessoal';if(norm(root)===home)return top==='documents'||top==='documentos'?'Documentos':'Pessoal';return space?.id==='rb-hub'?'Trabalho':space?.id==='condominio'?'Condomínio':space?.id==='projetos'?'Projetos':space?.id==='pessoal'?'Pessoal':sanitizeSegment(space?.name||'Geral');}
function inferSubject(file,root,area,space){const parts=relParts(root,file.path),usable=parts.slice(0,-1).map(sanitizeSegment).filter(Boolean),meaningful=usable.find(x=>!genericRoots.has(fold(x))&&!isTechnicalName(x));if(meaningful)return meaningful;if(area==='Trabalho'&&space?.id==='rb-hub')return'RB Hub';if(area==='Condomínio')return'Gestão do condomínio';if(area==='Projetos')return'Projetos';if(area==='Financeiro')return'Financeiro';return'Geral';}
function shouldPropose(file,root){const rel=relParts(root,file.path);if(rel.some(x=>isTechnicalName(x)))return false;if(rel.map(fold).includes('organizado'))return false;if(codeExts.has(file.ext))return false;if(['Dados'].includes(file.category)&&/package\.json|package-lock\.json|tsconfig|composer\.json/i.test(file.name))return false;if(norm(root)===home){const top=fold(rel[0]||'');return ['downloads','download','desktop','area de trabalho','documents','documentos','pictures','imagens','videos','vídeos','music','musica'].includes(top)||rel.length===1;}return true;}

export async function scanFolder(input,spaceId){const root=assertAllowedPath(input);if(norm(root)===home)throw new Error('A análise do perfil inteiro está bloqueada por segurança. Escolha Área de Trabalho, Downloads, Documentos ou outra pasta específica.');const sroot=await stat(root).catch(()=>null);if(!sroot?.isDirectory())throw new Error('A pasta informada não existe.');const state=await readState();const max=Number(state.settings?.maxScanFiles||5000);const files=[],folders=[],skipped={technical:[],repositories:[]};let truncated=false;async function walk(dir,depth=0){if(depth>12||files.length>=max){truncated=true;return;}const entries=await readdir(dir,{withFileTypes:true}).catch(()=>[]);for(const e of entries){if(files.length>=max){truncated=true;return;}const full=path.join(dir,e.name);if(e.isSymbolicLink())continue;if(e.isDirectory()){
        if(isTechnicalName(e.name)){skipped.technical.push(full);continue;}
        if(await isRepository(full)){skipped.repositories.push(full);continue;}
        folders.push(full);await walk(full,depth+1);continue;
      }
      if(e.isFile()){const st=await stat(full).catch(()=>null);if(!st)continue;files.push({id:id('file'),path:full,relativePath:path.relative(root,full),name:e.name,ext:path.extname(e.name).toLowerCase(),size:st.size,modifiedAt:st.mtime.toISOString(),createdAt:st.birthtime?.toISOString?.()||null,category:extCategory(path.extname(e.name).toLowerCase()),depth:path.relative(root,path.dirname(full)).split(path.sep).filter(Boolean).length});}}
  }await walk(root);const scan={id:id('scan'),spaceId,root,createdAt:new Date().toISOString(),fileCount:files.length,folderCount:folders.length,truncated,files,skipped:{technicalCount:skipped.technical.length,repositoryCount:skipped.repositories.length,technical:skipped.technical.slice(0,50),repositories:skipped.repositories.slice(0,50)}};await saveScan(scan);return scan;}

async function duplicateGroups(files){const bySize=new Map();for(const f of files){if(!f.size||!shouldPropose(f,path.dirname(f.path)))continue;const arr=bySize.get(f.size)||[];arr.push(f);bySize.set(f.size,arr);}const candidates=[...bySize.values()].filter(g=>g.length>1),groups=[];let hashed=0;for(const group of candidates){if(hashed>500)break;const byHash=new Map();for(const f of group){if(hashed++>500)break;const hash=await hashFile(f.path).catch(()=>null);if(!hash)continue;f.sha256=hash;const a=byHash.get(hash)||[];a.push(f);byHash.set(hash,a);}for(const [hash,items] of byHash)if(items.length>1)groups.push({hash,size:items[0].size,files:items});}return groups;}

export async function analyzeScan(scanId,spaceId){const state=await readState();const scan=state.scans.find(s=>s.id===scanId);if(!scan)throw new Error('Inventário não encontrado. Faça uma nova leitura da pasta.');const space=state.spaces.find(s=>s.id===(spaceId||scan.spaceId));if(!space)throw new Error('Contexto não encontrado.');const root=scan.root,destRoot=space.basePath?assertAllowedPath(space.basePath):path.join(root,'Organizado');const findings=[],operations=[],groups={};
  for(const f of scan.files){if(poorName(f.name)&&shouldPropose(f,root))findings.push({id:id('finding'),type:'poor_filename',severity:'medium',path:f.path,message:'Nome pouco descritivo ou com marcador informal de versão.'});if(!shouldPropose(f,root))continue;const year=String(new Date(f.modifiedAt).getFullYear()||new Date().getFullYear()),area=inferArea(f,root,space),subject=inferSubject(f,root,area,space),cleaned=poorName(f.name)?cleanFilename(f.name):f.name,target=path.join(destRoot,sanitizeSegment(area),sanitizeSegment(subject),year,f.category,cleaned);if(norm(target)===norm(f.path))continue;const confidence=area==='Entrada'?'medium':'high';findings.push({id:id('finding'),type:'organization_candidate',severity:'low',path:f.path,message:`${area} → ${subject} → ${year} → ${f.category}`});const op={id:id('op'),type:'MOVE_FILE',before:f.path,after:target,reason:`${area} → ${subject} → ${year} → ${f.category}`,confidence,recommended:confidence==='high',area,subject,year,category:f.category};operations.push(op);groups[area]=(groups[area]||0)+1;}
  const dups=await duplicateGroups(scan.files.filter(f=>shouldPropose(f,root)));for(const g of dups){findings.push({id:id('finding'),type:'duplicate',severity:'medium',message:`${g.files.length} arquivos idênticos (${formatBytes(g.size)}).`,hash:g.hash,paths:g.files.map(f=>f.path)});for(const f of g.files.slice(1)){const area=inferArea(f,root,space);operations.push({id:id('op'),type:'QUARANTINE_FILE',before:f.path,after:path.join(root,'_RB_Quarantine','Duplicados',f.name),reason:'Duplicado confirmado por SHA-256. Quarentena opcional; nunca excluir automaticamente.',confidence:'medium',recommended:false,sha256:g.hash,area:'Duplicados',subject:area,year:'',category:'Duplicados'});}}
  const plan={id:id('plan'),scanId:scan.id,spaceId:space.id,spaceName:space.name,root,createdAt:new Date().toISOString(),policy:space.policy,destinationRoot:destRoot,findings,operations,groups,status:'preview',skipped:scan.skipped||{}};await savePlan(plan);return plan;}

function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`;}
export async function executePlan(){throw new Error('Execução legada desativada permanentemente por segurança. Use startExecutionJob(), que exige checkpoint físico e transferência validada por SHA-256.');}
export async function rollbackTransaction(){throw new Error('Rollback legado desativado permanentemente por segurança. Use rollbackTransactionSafe() ou o Recovery Center.');}
export function commonFolders(){return{Home:home,Downloads:path.join(home,'Downloads'),Documents:path.join(home,'Documents'),Desktop:path.join(home,'Desktop'),Pictures:path.join(home,'Pictures')};}
export async function getWorkspaceSummary(){const state=await readState();return{spaces:state.spaces,scans:state.scans.slice(0,8).map(s=>({id:s.id,spaceId:s.spaceId,root:s.root,createdAt:s.createdAt,fileCount:s.fileCount,folderCount:s.folderCount,truncated:s.truncated,skipped:s.skipped})),transactions:state.transactions.slice(0,20),counts:{spaces:state.spaces.length,scans:state.scans.length,transactions:state.transactions.length}};}
